In [86]:
import urllib
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
import random

# connexion avec la base de données
from pymongo import MongoClient

In [87]:
#df_more = pd.read_csv('Indeed_Project_3_df_more_long_not_cleaned.csv')

In [110]:
df_1 = pd.read_csv('20220226_Indeed_Project_3_df_more_long_not_cleaned_1634_lignes.csv')
df_1.shape

(1633, 7)

In [111]:
df_2 = pd.read_csv('20220226_Indeed_Project_3_df_more_long_not_cleaned_paris.csv')
df_2.shape

(2541, 7)

In [112]:
df_more = df_1.append(df_2)
df_more.drop('Unnamed: 0', axis=1, inplace=True)
df_more.shape

(4174, 6)

In [113]:
df_more.drop_duplicates()
df_more.shape

(4174, 6)

In [114]:
df_more.head()

,Title,Location,Company,Rating,Salary,Synopsis
0,Data analyst campagne publicitaire Pinterest à...,France,Teleperformance Portugal,3.5,None,"Vous êtes francophone, passionné par le market..."
1,Data Analyst H/F,37000 Tours,ACII,None,35 000 € - 45 000 € par an,Chez nous on dit ce que l'on fait et on fait c...
2,Data Analyst,Tours (37),Daher,3.5,None,Job Title\nData Analyst\nContract\nPermanent\n...
3,Data Analyst Marketing F/H,Tours (37),Kaino Consulting,None,None,Data Analyst Marketing F/H\nRef. Apec : 167730...
4,Data Analyst Marketing F/H,37000 Tours,Avanci,4.4,None,L'entreprise\nAvec une recette unique dans le ...

In [115]:
print (df_more.shape)
print (df_more[df_more.Salary != 'None'].shape)

(4174, 6)
(1074, 6)

In [116]:
df_more_2 = df_more[df_more.Salary != 'None'].drop_duplicates().dropna()
print (df_more_2.shape)

(760, 6)

In [117]:
df_more_2['Salary']

1       35 000 € - 45 000 € par an
47                 45 000 € par an
50          350 € - 450 € par jour
51          400 € - 550 € par jour
54      38 000 € - 40 000 € par an
                   ...
1976              1 200 € par mois
1987    40 000 € - 60 000 € par an
2011    50 000 € - 55 000 € par an
2013    45 000 € - 50 000 € par an
2029        400 € - 550 € par jour
Name: Salary, Length: 760, dtype: object

In [124]:
df_more_2[df_more_2['Salary'].str.contains('heure')]

,Title,Location,Company,Rating,Salary,Synopsis
153,Analyste data marketing H/F,Lyon (69),Proman,3.5,"18,14 € par heure","Proman Expertise, agence spécialisée « hautes ..."
185,Data Analyst H/F,33000 Bordeaux,Betclic Group,4.2,25 € par heure,WE ARE BETCLIC\n\nEntreprise française leader ...
650,Développeur .Net H/F,33300 Bordeaux,Betclic Group,4.2,25 € par heure,WE ARE BETCLIC\n\nEntreprise française leader ...
1048,Senior Data Scientist H/F,33300 Bordeaux,Betclic Group,4.2,25 € par heure,WE ARE BETCLIC\n\nEntreprise française leader ...
413,Ingénieur DevOps H/F,Torcy (77),ABIL INTERIM,None,40 € par heure,Nous recherchons pour l’un de nos clients un I...
1938,DATA ANALYST,75019 Paris 19e,Groupe Europa,None,30 € par heure,"Vos missions\nPréparation, l'implémentation et..."

In [123]:
df_more_2[df_more_2['Salary'].str.contains('semaine')]

,Title,Location,Company,Rating,Salary,Synopsis
122,Analyst Data [SQL / Python] (H/F),Lyon (69),Insitoo,None,350 € par semaine,"Basée à Lille, Lyon, Grenoble et Bruxelles, In..."
274,Data Analysts/Data Engineer - REF AP - Freelan...,Hybrid remote in 44000 Nantes,Humaniance,None,300 € - 500 € par semaine,"Pour un de nos clients grand-comptes, nous rec..."
516,Developpeur Web H/F en Freelance,Paris (75),B&CO Formation,None,1 000 € par semaine,Bonjour !Nous recherchons un développeur web i...
33,Développeur PHP Symfony / API,Paris (75),Eyetech Solutions,None,350 € - 500 € par semaine,Un de nos client final recrute actuellement un...
564,Developpeur Front end,Paris (75),Eyetech Solutions,None,300 € - 450 € par semaine,En tant que Développeur avec une solide expéri...
580,Senior Développeur iOS Freelance (remote),Télétravail in Paris (75),NonStop Consulting,None,400 € - 650 € par semaine,Vous souhaitez évoluer en équipe avec des coll...

In [125]:
df_mois = df_more_2[df_more_2['Salary'].str.contains('mois')]
df_mois.shape

(63, 6)

In [126]:
df_mois

,Title,Location,Company,Rating,Salary,Synopsis
90,Data Analyst & BI SAMSUNG,78140 Vélizy-Villacoublay,Service Innovation Group,3.8,2 500 € - 2 800 € par mois,Rejoignez la nouvelle équipe force de vente SA...
396,Concepteur développeur logiciel objet junior,Télétravail in 37300 Joué-lés-Tours,EURAXIPHARMA,None,1 700 € - 2 000 € par mois,Expérience minimum 1 à 3ansFront End et back E...
466,Reconversion + poste d'ingénieur(e) développeu...,92240 Malakoff,ISIKA SAS,None,2 700 € - 3 500 € par mois,Vous serez intégré au sein d'une équipe agile ...
480,Developpeur Web H/F,92200 Neuilly-sur-Seine,StedY,None,2 000 € - 2 500 € par mois,Pour notre client grand acteur de la finance b...
489,Développeur Front-End H/F,75015 Paris 15e,Pixalione,3.0,1 000 € par mois,"Entreprise : Crée en 2007, Pixalione est spéci..."
...,...,...,...,...,...,...
1466,Développeur Fullstack Senior - CDI,Paris (75),ShareGroop,None,2 500 € - 4 000 € par mois,About Atos\n\nAtos is a global leader in digit...
1501,Analyste données Énergie F/H,75019 Paris,Enercoop,None,2 600 € - 3 000 € par mois,Etablissement : Enercoop NationalType de contr...
1722,Apprenti(e) Data Analyst,Île-de-France,OpenClassrooms,None,2 062 € - 3 965 € par mois,Référence de l’offre\n2200015Y\nType de contra...
1756,Apprenti(e) Data Analyst,Île-de-France,OpenClassrooms,None,2 062 € - 3 965 € par mois,PayPlug est une solution de paiement omnicanal...
1976,Data analyst (Stage),75011 Paris 11e,Spark,None,1 200 € par mois,️spark en quelques mots\n\nNotre mission: acco...

In [127]:
df_more_2 = df_more_2[df_more_2.Salary.str.contains("heure") == False]
df_more_2 = df_more_2[df_more_2.Salary.str.contains("semaine") == False]
df_more_2 = df_more_2[df_more_2.Salary.str.contains("mois") == False]
print (df_more_2.shape)
df_more_2.head()

(685, 6)

,Title,Location,Company,Rating,Salary,Synopsis
1,Data Analyst H/F,37000 Tours,ACII,None,35 000 € - 45 000 € par an,Chez nous on dit ce que l'on fait et on fait c...
47,Data Analyst H/F,75007 Paris 7e,NOT SO DARK,None,45 000 € par an,Présentation du Groupe\nAir Liquide est un lea...
50,DATA ANALYST / SCIENTIST (H/F) / Freelance,Saint-Maur-des-Fossés (94),FRISBEE PROFILING,None,350 € - 450 € par jour,DATA ANALYST - PYTHON H/F (NUMÉRO DE L'EMPLOI ...
51,TRES URGENT - DATA ANALYST - 6 MOIS RECONDUCTI...,Télétravail in Paris (75),ALLEGIS GROUP,None,400 € - 550 € par jour,DATA ANALYST - PYTHON H/F (NUMÉRO DE L'EMPLOI ...
54,DATA ANALYST H/F,Paris (75)+ 1 lieu,Clint & Associés,None,38 000 € - 40 000 € par an,IMMOBILIER / MAINTENANCE / TRAVAUX\n PARIS\nCD...

In [128]:
def salary_stripper(dataframe, column):
    dataframe[str(column)] = dataframe[str(column)].replace({'\€':''}, regex = True)
    dataframe[str(column)].replace(regex=True,inplace=True,to_replace=r'\D',value=r' ')
    dataframe[str(column)] = dataframe[str(column)].str.replace(' ',',')
    dataframe = dataframe.join(dataframe[str(column)].str.split(',,,', 1, expand=True).rename(columns={0:'Low', 1:'High'}))
    dataframe['Low'] = dataframe['Low'].str.replace(',','')
    dataframe['Low'] = dataframe['Low'].astype('float64')
    dataframe.drop(str(column), axis=1, inplace=True)
    dataframe['High'] = dataframe['High'].str.replace(',','')
    dataframe['High'] = dataframe['High'].apply(pd.to_numeric)
    dataframe['Salaire_annuel_moyen'] = dataframe[['Low', 'High']].mean(axis=1)
    dataframe = dataframe.drop(columns=['Rating','Low','High'])
    return dataframe

In [129]:
df_more = salary_stripper(df_more_2, 'Salary')
df_more.shape

(773, 5)

In [130]:
df_more.head()

,Title,Location,Company,Synopsis,Salaire_annuel_moyen
1,Data Analyst H/F,37000 Tours,ACII,Chez nous on dit ce que l'on fait et on fait c...,40000.0
6,Développeur Java & PHP - Full stack - H/F,75019 Paris 19e,Golden Bees,"Nous recherchons pour l'un de nos clients, un ...",34000.0
8,Développeur COBOL - RDZ (H/F) / Freelance,Paris (75),HR-TEAM,"MISSION\nDocaposte Trust & Sign, filiale de Do...",410.0
10,Développeur Python/ Django (H/F) / Freelance,Paris (75),HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,475.0
11,Devops Engineer (H/F) / Freelance,Paris (75),HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,575.0

In [131]:
df_mois_2 = salary_stripper(df_mois, 'Salary')
df_mois_2.head()

,Title,Location,Company,Synopsis,Salaire_annuel_moyen
90,Data Analyst & BI SAMSUNG,78140 Vélizy-Villacoublay,Service Innovation Group,Rejoignez la nouvelle équipe force de vente SA...,2650.0
396,Concepteur développeur logiciel objet junior,Télétravail in 37300 Joué-lés-Tours,EURAXIPHARMA,Expérience minimum 1 à 3ansFront End et back E...,1850.0
401,Développeur Informatique middle (H/F),94150 Rungis,GIF Emploi - TIM,Vous avez une bonne appétence dans le domaine ...,2650.0
466,Reconversion + poste d'ingénieur(e) développeu...,92240 Malakoff,ISIKA SAS,Vous serez intégré au sein d'une équipe agile ...,3100.0
480,Developpeur Web H/F,92200 Neuilly-sur-Seine,StedY,Pour notre client grand acteur de la finance b...,2250.0

In [133]:
# En multipliant les salaires par 12, on obtient la valeur de la moyenne annuelle.
df_mois_2['Salaire_annuel_moyen'] = df_mois_2['Salaire_annuel_moyen'] * 12
df_mois_2.head()

,Title,Location,Company,Synopsis,Salaire_annuel_moyen
90,Data Analyst & BI SAMSUNG,78140 Vélizy-Villacoublay,Service Innovation Group,Rejoignez la nouvelle équipe force de vente SA...,31800.0
396,Concepteur développeur logiciel objet junior,Télétravail in 37300 Joué-lés-Tours,EURAXIPHARMA,Expérience minimum 1 à 3ansFront End et back E...,22200.0
401,Développeur Informatique middle (H/F),94150 Rungis,GIF Emploi - TIM,Vous avez une bonne appétence dans le domaine ...,31800.0
466,Reconversion + poste d'ingénieur(e) développeu...,92240 Malakoff,ISIKA SAS,Vous serez intégré au sein d'une équipe agile ...,37200.0
480,Developpeur Web H/F,92200 Neuilly-sur-Seine,StedY,Pour notre client grand acteur de la finance b...,27000.0

In [134]:
# Maintenant nous ajoutons le df qui avait les salaires par mois au df plus grand. 
df_more = df_more.append(df_mois_2)
df_more.shape

(838, 5)

In [135]:
#Nous ajoutons une nouvelle colonne avec uniquement le numéro du département 
# et nous supprimons la colonne appelée Location.
df_more['Département'] = df_more['Location'].str.extract(r'(\d{2})', expand=False)
df_more = df_more.drop(columns=['Location'])

In [146]:
df_more.isna().sum()

Title                    0
Company                  0
Synopsis                 0
Salaire_annuel_moyen     0
Département             16
dtype: int64

In [149]:
# Nous supprimons les lignes qui n'ont pas de numéro de département.
df_more = df_more[df_more['Département'].notna()]
df_more.shape

(822, 5)

In [150]:
df_more.head(20)

,Title,Company,Synopsis,Salaire_annuel_moyen,Département
1,Data Analyst H/F,ACII,Chez nous on dit ce que l'on fait et on fait c...,40000.0,37
6,Développeur Java & PHP - Full stack - H/F,Golden Bees,"Nous recherchons pour l'un de nos clients, un ...",34000.0,75
8,Développeur COBOL - RDZ (H/F) / Freelance,HR-TEAM,"MISSION\nDocaposte Trust & Sign, filiale de Do...",410.0,75
10,Développeur Python/ Django (H/F) / Freelance,HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,475.0,75
11,Devops Engineer (H/F) / Freelance,HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,575.0,75
17,Développeur Front-End H/F,My PepIT,Poste : Développeur Frontend H/FDomaine d’acti...,60000.0,92
18,Développeur informatique H/F,Upswing Engineering,Upswing Engineering est une société d'ingénier...,50000.0,92
26,DÉVELOPPEUR BACK-END PYTHON | FASHIONTECH,Urban Linker,PARIS\n\nCDI\n\nTECH\n\n45K À 60K €\nJE PARRAI...,52500.0,75
28,Développeur .Net WPF Senior / Freelance,GROUPE HN,C# .technique/développement NET WPF Dans ce ca...,345.0,75
31,Développeur Java H/F,My PepIT,Poste : Développeur Java H/FDomaine d’activité...,60000.0,92
34,Devops Engineer (H/F) (IT),HR-TEAM,"Description du poste :\n\nDéployer, stabiliser...",57500.0,75
36,Devops AWS (H/F) (IT),HR-TEAM,Description du poste :\n\nIntégrer les différe...,57500.0,75
37,Développeur Front-End H/F,HCUB3,Description du poste :\n\nIntégrer les différe...,43075.5,75
47,Data Analyst H/F,NOT SO DARK,Présentation du Groupe\nAir Liquide est un lea...,45000.0,75
50,DATA ANALYST / SCIENTIST (H/F) / Freelance,FRISBEE PROFILING,DATA ANALYST - PYTHON H/F (NUMÉRO DE L'EMPLOI ...,400.0,94
51,TRES URGENT - DATA ANALYST - 6 MOIS RECONDUCTI...,ALLEGIS GROUP,DATA ANALYST - PYTHON H/F (NUMÉRO DE L'EMPLOI ...,475.0,75
53,Lead développeur Java H/F,Levertech Consulting,"Levertech consulting, cabinet de conseil en SI...",56000.0,92
54,DATA ANALYST H/F,Clint & Associés,IMMOBILIER / MAINTENANCE / TRAVAUX\n PARIS\nCD...,39000.0,75
55,Développeur .NET H/F,INFORMATIS,Dans le cadre d’un important projet avec un cl...,40000.0,75
56,Développeur web full - stack (h/f),SERVICES AND CO,Présentation de l'entreprise:\n\nServices and ...,42000.0,77

In [151]:
df_more.to_csv('20220227_Indeed_Project_3_df_cleaned.csv', encoding='utf-8')

In [157]:
df_more = pd.read_csv('20220227_Indeed_Project_3_df_cleaned.csv')
df_more.head()

,Unnamed: 0,Title,Company,Synopsis,Salaire_annuel_moyen,Département
0,1,Data Analyst H/F,ACII,Chez nous on dit ce que l'on fait et on fait c...,40000.0,37
1,6,Développeur Java & PHP - Full stack - H/F,Golden Bees,"Nous recherchons pour l'un de nos clients, un ...",34000.0,75
2,8,Développeur COBOL - RDZ (H/F) / Freelance,HR-TEAM,"MISSION\nDocaposte Trust & Sign, filiale de Do...",410.0,75
3,10,Développeur Python/ Django (H/F) / Freelance,HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,475.0,75
4,11,Devops Engineer (H/F) / Freelance,HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,575.0,75

In [158]:
df_more.drop('Unnamed: 0', axis=1, inplace=True)

In [188]:
df_more.head()

,Title,Company,Synopsis,Salaire_annuel_moyen,Département
0,Data Analyst H/F,ACII,Chez nous on dit ce que l'on fait et on fait c...,40000.0,37
1,Développeur Java & PHP - Full stack - H/F,Golden Bees,"Nous recherchons pour l'un de nos clients, un ...",34000.0,75
2,Développeur COBOL - RDZ (H/F) / Freelance,HR-TEAM,"MISSION\nDocaposte Trust & Sign, filiale de Do...",410.0,75
3,Développeur Python/ Django (H/F) / Freelance,HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,475.0,75
4,Devops Engineer (H/F) / Freelance,HR-TEAM,Le rôle: Ingénieur DevOps (F/H)\nAfin de renfo...,575.0,75

In [189]:
df_more.shape

(822, 5)

In [160]:
df_more['Title'].value_counts().head(40)

Developpeur Web H/F                                                15
Développeur Full Stack H/F                                         14
Développeur Front-End H/F                                          13
Data Analyst H/F                                                   13
Data Scientist H/F                                                 11
Urgent - Développeur Java / Angular /.Net & Power BI / Freel...     8
Développeur domain driven design                                    5
Lead Développeur JAVA H/F                                           5
Développeur Fullstack Senior - CDI                                  5
DEVELOPPEUR WINDEV - PARIS                                          5
Data Analyst F/H                                                    5
Développeur Java Fullstack                                          5
Développeur-euse OCaml                                              5
Développeur NTIC                                                    5
Senior Business Developer - Agence Digitale/Web | CDI               5
Développeur Windev H/F                                              5
MISSION DEVOPS AWS RUN / Freelance                                  4
Développeur Big Data Confirmé / Freelance                           4
Développeur Android pour Formation / Freelance                      4
Data Analyst                                                        4
Développeur Web pour Formation (REACT) / Freelance                  4
Développeur PHP                                                     4
Développeur.se Javascript / Python - Finance / Freelance            4
Consultant Data et BI F/H                                           4
Un Développeur Full stack DotNet, Angular (H/F)                     4
Développeur PHP H/F                                                 4
Développeur Fullstack Java / Angular / Freelance                    4
DATA ANALYST / SCIENTIST (H/F) / Freelance                          4
Développeur Android Kotlin Sénior / Freelance                       3
Développeur Python / Freelance                                      3
Lead dev Java / Freelance                                           3
Developpeur(euse).net                                               3
Développeur(se) FullStack .NET / Angular confirmé(e) – édite...     3
Lead dev angular / Freelance                                        3
Développeur Java Spring expérimenté                                 3
Ingénieur en développement Full Stack - Intégration Devops K...     3
Data Scientist (H/F)                                                3
Développeur Fullstack / Freelance                                   3
BUSINESS DÉVELOPPEUR EUROPE                                         3
Developpeur Web H/F Odoo                                            3
Name: Title, dtype: int64

In [190]:
# Connection au serveur MongoDB
client = MongoClient('mongodb://localhost/')
bdd = 'projet_7_JNTC'
collection = 'scraping_indeed'

# Récupération de la BDD 
db = client[bdd]
print(db)

# Récupération de la collection 
collec = db[collection]
print(collec)

#collec.insert_many(df_more.to_dict('records'))

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'projet_7_JNTC')
Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'projet_7_JNTC'), 'scraping_indeed')

In [191]:
def get_Data(txt):
    Data_list = re.findall('(?i)(Data)',txt)
    return Data_list

def get_Data_Analyst(txt):
    Data_Analyst_list = re.findall('(?i)(Data Analyst)',txt)
    return Data_Analyst_list

def get_Data_Scientist(txt):
    Data_Scientist_list = re.findall('(?i)(Data Scientist)',txt)
    return Data_Scientist_list

def get_Developpeur(txt):
    Developpeur_list = re.findall('(?i)(Développeur)',txt)
    return Developpeur_list

def get_Business_Intelligence(txt):
    Business_Intelligence_list = re.findall('(?i)(Business Intelligence)',txt)
    return Business_Intelligence_list

def get_Consultant(txt):
    Consultant_list = re.findall('(?i)(Consultant)',txt)
    return Consultant_list

def get_Senior(txt):
    Senior_list = re.findall('(?i)(Senior)',txt)
    return Senior_list

def get_word_Debutant(txt):
    Debutant_list = re.findall('(?i)(Débutant)',txt)
    return Debutant_list

def get_Cadre(txt):
    Cadre_list = re.findall('(?i)(Cadre)',txt)
    return Cadre_list


def get_word_Engineer(txt):
    Engineer_list = re.findall('(?i)(Engineer)',txt)
    return Engineer_list

def get_big_data(txt):
    big_data_list = re.findall('(?i)(big data)',txt)
    return big_data_list

def get_word_NLP(txt):
    NLP_list = re.findall('(?i)(NLP)',txt)
    return NLP_list

def get_word_CDI(txt):
    CDI_list = re.findall('(?i)(CDI)',txt)
    return CDI_list

def get_word_CDD(txt):
    CDD_list = re.findall('(?i)(CDD)',txt)
    return CDD_list

def get_word_freelance(txt):
    freelance_list = re.findall('(?i)(freelance)',txt)
    return freelance_list



def get_BacPlus5(txt):
    BacPlus5_list = re.findall('(?i)(Bac\+5)',txt)
    return BacPlus5_list

def get_BacPlus4(txt):
    BacPlus4_list = re.findall('(?i)(Bac\+4)',txt)
    return BacPlus4_list

def get_BacPlus3(txt):
    BacPlus3_list = re.findall('(?i)(Bac\+3)',txt)
    return BacPlus3_list

def get_BacPlus2(txt):
    BacPlus2_list = re.findall('(?i)(Bac\+2)',txt)
    return BacPlus2_list

def get_word_Python(txt):
    Python_list = re.findall('(?i)(Python)',txt)
    return Python_list

def get_word_Pyspark(txt):
    Pyspark_list = re.findall('(?i)(Pyspark)',txt)
    return Pyspark_list

def get_word_Java(txt):
    Java_list = re.findall('(?i)(Java)',txt)
    return Java_list

def get_word_Julia(txt):
    Julia_list = re.findall('(?i)(Julia)',txt)
    return Julia_list

def get_word_JavaScript(txt):
    JavaScript_list = re.findall('(?i)(JavaScript)',txt)
    return JavaScript_list

def get_word_PHP(txt):
    PHP_list = re.findall('(?i)(PHP)',txt)
    return PHP_list

def get_CPlusPlus(txt):
    CPlusPlus_list = re.findall('(?i)(C\+\+)',txt)
    return CPlusPlus_list

def get_SQL(txt):
    SQL_list = re.findall('(?i)(SQL)',txt)
    return SQL_list

def get_NoSQL(txt):
    NoSQL_list = re.findall('(?i)(NoSQL)',txt)
    return NoSQL_list


def get_word_AWS(txt):
    AWS_list = re.findall('(?i)(AWS)',txt)
    return AWS_list

def get_word_Azure(txt):
    Azure_list = re.findall('(?i)(Azure)',txt)
    return Azure_list

def get_Kafka(txt):
    Kafka_list = re.findall('(?i)(Kafka)',txt)
    return Kafka_list

def get_SQL_Server(txt):
    SQL_Server_list = re.findall('(?i)(SQL Server)',txt)
    return SQL_Server_list

def get_machine_learning(txt):
    machine_learning_list = re.findall('(?i)(machine learning)',txt)
    return machine_learning_list

def get_deep_learning(txt):
    deep_learning_list = re.findall('(?i)(deep learning)',txt)
    return deep_learning_list

def get_English(txt):
    English_list = re.findall('(?i)(English)',txt)
    return English_list

In [192]:
# Ici nous testons toutes les fonctions
em= " helo :) Data analyst H/F / Freelance, Engineer big data, Bac+5, Cadre"
print(get_Data_Analyst(em))

['Data analyst']

In [193]:
# Modification des features liés au Title dans la BDD mongo
for doc in collec.find():
    txt = doc['Title']
    
    Data = get_Data(txt)
    Data_Analyst = get_Data_Analyst(txt)
    Data_Scientist = get_Data_Scientist(txt)
    Developpeur =get_Developpeur(txt)
    Business_Intelligence = get_Business_Intelligence(txt)
    
    Consultant = get_Consultant(txt)
    Senior = get_Senior(txt)  
    word_Engineer = get_word_Engineer(txt)
    word_freelance = get_word_freelance(txt)
    
    
    id = doc['_id']

    print(id, Data)

    # Les lignes suivantes doivent être décochées en tant que commentaire 
    # afin de charger les nouvelles features dans la nouvelle collection        

    #collec.update_one({'_id': id}, {"$set": {"Titre/Data": len(Data)}})
    #collec.update_one({'_id': id}, {"$set": {"Titre/Data Analyst": len(Data_Analyst)}})
    #collec.update_one({'_id': id}, {"$set": {"Titre/Data Scientist": len(Data_Scientist)}})
    #collec.update_one({'_id': id}, {"$set": {"Titre/Developpeur": len(Developpeur)}})
    #collec.update_one({'_id': id}, {"$set": {"Titre/Business Intelligence": len(Business_Intelligence)}})    
    #collec.update_one({'_id': id}, {"$set": {"Titre/Consultant": len(Consultant)}})
    #collec.update_one({'_id': id}, {"$set": {"Titre/Senior": len(Senior)}})   
    #collec.update_one({'_id': id}, {"$set": {"Titre/Engineer": len(word_Engineer)}})
    #collec.update_one({'_id': id}, {"$set": {"Titre/freelance": len(word_freelance)}})

621b885c6919b49c17d477b3 []
621b885c6919b49c17d477b4 []
621b885c6919b49c17d477b5 []
621b885c6919b49c17d477b6 []
621b885c6919b49c17d477b7 []
621b885c6919b49c17d477b8 []
621b885c6919b49c17d477b9 []
621b885c6919b49c17d477ba []
621b885c6919b49c17d477bb []
621b885c6919b49c17d477bc []
621b885c6919b49c17d477bd []
621b885c6919b49c17d477be []
621b885c6919b49c17d477bf []
621b885c6919b49c17d477c0 []
621b885c6919b49c17d477c1 []
621b885c6919b49c17d477c2 []
621b885c6919b49c17d477c3 []
621b885c6919b49c17d477c4 []
621b885c6919b49c17d477c5 []
621b885c6919b49c17d477c6 []
621b885c6919b49c17d477c7 []
621b885c6919b49c17d477c8 []
621b885c6919b49c17d477c9 []
621b885c6919b49c17d477ca []
621b885c6919b49c17d477cb []
621b885c6919b49c17d477cc []
621b885c6919b49c17d477cd []
621b885c6919b49c17d477ce []
621b885c6919b49c17d477cf []
621b885c6919b49c17d477d0 []
621b885c6919b49c17d477d1 []
621b885c6919b49c17d477d2 []
621b885c6919b49c17d477d3 []
621b885c6919b49c17d477d4 []
621b885c6919b49c17d477d5 []
621b885c6919b49c17d477d6 []
621b885c6919b49c17d477d7 []
621b885c6919b49c17d477d8 []
621b885c6919b49c17d477d9 []
621b885c6919b49c17d477da []
621b885c6919b49c17d477db []
621b885c6919b49c17d477dc []
621b885c6919b49c17d477dd []
621b885c6919b49c17d477de []
621b885c6919b49c17d477df []
621b885c6919b49c17d477e0 []
621b885c6919b49c17d477e1 []
621b885c6919b49c17d477e2 []
621b885c6919b49c17d477e3 []
621b885c6919b49c17d477e4 []
621b885c6919b49c17d477e5 []
621b885c6919b49c17d477e6 []
621b885c6919b49c17d477e7 []
621b885c6919b49c17d477e8 []
621b885c6919b49c17d477e9 []
621b885c6919b49c17d477ea []
621b885c6919b49c17d477eb []
621b885c6919b49c17d477ec []
621b885c6919b49c17d477ed []
621b885c6919b49c17d477ee []
621b885c6919b49c17d477ef []
621b885c6919b49c17d477f0 []
621b885c6919b49c17d477f1 []
621b885c6919b49c17d477f2 []
621b885c6919b49c17d477f3 []
621b885c6919b49c17d477f4 []
621b885c6919b49c17d477f5 []
621b885c6919b49c17d477f6 []
621b885c6919b49c17d477f7 []
621b885c6919b49c17d477f8 []
621b885c6919b49c17d477f9 []
621b885c6919b49c17d477fa []
621b885c6919b49c17d477fb []
621b885c6919b49c17d477fc []
621b885c6919b49c17d477fd []
621b885c6919b49c17d477fe []
621b885c6919b49c17d477ff []
621b885c6919b49c17d47800 []
621b885c6919b49c17d47801 []
621b885c6919b49c17d47802 []
621b885c6919b49c17d47803 []
621b885c6919b49c17d47804 []
621b885c6919b49c17d47805 []
621b885c6919b49c17d47806 []
621b885c6919b49c17d47807 []
621b885c6919b49c17d47808 []
621b885c6919b49c17d47809 []
621b885c6919b49c17d4780a []
621b885c6919b49c17d4780b []
621b885c6919b49c17d4780c []
621b885c6919b49c17d4780d []
621b885c6919b49c17d4780e []
621b885c6919b49c17d4780f []
621b885c6919b49c17d47810 []
621b885c6919b49c17d47811 []
621b885c6919b49c17d47812 []
621b885c6919b49c17d47813 []
621b885c6919b49c17d47814 []
621b885c6919b49c17d47815 []
621b885c6919b49c17d47816 []
621b885c6919b49c17d47817 []
621b885c6919b49c17d47818 []
621b885c6919b49c17d47819 []
621b885c6919b49c17d4781a []
621b885c6919b49c17d4781b []
621b885c6919b49c17d4781c []
621b885c6919b49c17d4781d []
621b885c6919b49c17d4781e []
621b885c6919b49c17d4781f []
621b885c6919b49c17d47820 []
621b885c6919b49c17d47821 []
621b885c6919b49c17d47822 []
621b885c6919b49c17d47823 []
621b885c6919b49c17d47824 []
621b885c6919b49c17d47825 []
621b885c6919b49c17d47826 []
621b885c6919b49c17d47827 []
621b885c6919b49c17d47828 []
621b885c6919b49c17d47829 []
621b885c6919b49c17d4782a []
621b885c6919b49c17d4782b []
621b885c6919b49c17d4782c []
621b885c6919b49c17d4782d []
621b885c6919b49c17d4782e []
621b885c6919b49c17d4782f []
621b885c6919b49c17d47830 []
621b885c6919b49c17d47831 []
621b885c6919b49c17d47832 []
621b885c6919b49c17d47833 []
621b885c6919b49c17d47834 []
621b885c6919b49c17d47835 []
621b885c6919b49c17d47836 []
621b885c6919b49c17d47837 []
621b885c6919b49c17d47838 []
621b885c6919b49c17d47839 []
621b885c6919b49c17d4783a []
621b885c6919b49c17d4783b []
621b885c6919b49c17d4783c []
621b885c6919b49c17d4783d []
621b885c6919b49c17d4783e []
621b885c6919b49c17d4783f []
621b885c6919b49c17d47840 []
621b885c6919b49c17d47841 []
621b885c6919b49c17d47842 []
621b885c6919b49c17d47843 []
621b885c6919b49c17d47844 []
621b885c6919b49c17d47845 []
621b885c6919b49c17d47846 []
621b885c6919b49c17d47847 []
621b885c6919b49c17d47848 []
621b885c6919b49c17d47849 []
621b885c6919b49c17d4784a []
621b885c6919b49c17d4784b []
621b885c6919b49c17d4784c []
621b885c6919b49c17d4784d []
621b885c6919b49c17d4784e []
621b885c6919b49c17d4784f []
621b885c6919b49c17d47850 []
621b885c6919b49c17d47851 []
621b885c6919b49c17d47852 []
621b885c6919b49c17d47853 []
621b885c6919b49c17d47854 []
621b885c6919b49c17d47855 []
621b885c6919b49c17d47856 []
621b885c6919b49c17d47857 []
621b885c6919b49c17d47858 []
621b885c6919b49c17d47859 []
621b885c6919b49c17d4785a []
621b885c6919b49c17d4785b []
621b885c6919b49c17d4785c []
621b885c6919b49c17d4785d []
621b885c6919b49c17d4785e []
621b885c6919b49c17d4785f []
621b885c6919b49c17d47860 []
621b885c6919b49c17d47861 []
621b885c6919b49c17d47862 []
621b885c6919b49c17d47863 []
621b885c6919b49c17d47864 []
621b885c6919b49c17d47865 []
621b885c6919b49c17d47866 []
621b885c6919b49c17d47867 []
621b885c6919b49c17d47868 []
621b885c6919b49c17d47869 []
621b885c6919b49c17d4786a []
621b885c6919b49c17d4786b []
621b885c6919b49c17d4786c []
621b885c6919b49c17d4786d []
621b885c6919b49c17d4786e []
621b885c6919b49c17d4786f []
621b885c6919b49c17d47870 []
621b885c6919b49c17d47871 []
621b885c6919b49c17d47872 []
621b885c6919b49c17d47873 []
621b885c6919b49c17d47874 []
621b885c6919b49c17d47875 []
621b885c6919b49c17d47876 []
621b885c6919b49c17d47877 []
621b885c6919b49c17d47878 []
621b885c6919b49c17d47879 []
621b885c6919b49c17d4787a []
621b885c6919b49c17d4787b []
621b885c6919b49c17d4787c []
621b885c6919b49c17d4787d []
621b885c6919b49c17d4787e []
621b885c6919b49c17d4787f []
621b885c6919b49c17d47880 []
621b885c6919b49c17d47881 []
621b885c6919b49c17d47882 []
621b885c6919b49c17d47883 []
621b885c6919b49c17d47884 []
621b885c6919b49c17d47885 []
621b885c6919b49c17d47886 []
621b885c6919b49c17d47887 []
621b885c6919b49c17d47888 []
621b885c6919b49c17d47889 []
621b885c6919b49c17d4788a []
621b885c6919b49c17d4788b []
621b885c6919b49c17d4788c []
621b885c6919b49c17d4788d []
621b885c6919b49c17d4788e []
621b885c6919b49c17d4788f []
621b885c6919b49c17d47890 []
621b885c6919b49c17d47891 []
621b885c6919b49c17d47892 []
621b885c6919b49c17d47893 []
621b885c6919b49c17d47894 []
621b885c6919b49c17d47895 []
621b885c6919b49c17d47896 []
621b885c6919b49c17d47897 []
621b885c6919b49c17d47898 []
621b885c6919b49c17d47899 []
621b885c6919b49c17d4789a []
621b885c6919b49c17d4789b []
621b885c6919b49c17d4789c []
621b885c6919b49c17d4789d []
621b885c6919b49c17d4789e []
621b885c6919b49c17d4789f []
621b885c6919b49c17d478a0 []
621b885c6919b49c17d478a1 []
621b885c6919b49c17d478a2 []
621b885c6919b49c17d478a3 []
621b885c6919b49c17d478a4 []
621b885c6919b49c17d478a5 []
621b885c6919b49c17d478a6 []
621b885c6919b49c17d478a7 []
621b885c6919b49c17d478a8 []
621b885c6919b49c17d478a9 []
621b885c6919b49c17d478aa []
621b885c6919b49c17d478ab []
621b885c6919b49c17d478ac []
621b885c6919b49c17d478ad []
621b885c6919b49c17d478ae []
621b885c6919b49c17d478af []
621b885c6919b49c17d478b0 []
621b885c6919b49c17d478b1 []
621b885c6919b49c17d478b2 []
621b885c6919b49c17d478b3 []
621b885c6919b49c17d478b4 []
621b885c6919b49c17d478b5 []
621b885c6919b49c17d478b6 []
621b885c6919b49c17d478b7 []
621b885c6919b49c17d478b8 []
621b885c6919b49c17d478b9 []
621b885c6919b49c17d478ba []
621b885c6919b49c17d478bb []
621b885c6919b49c17d478bc []
621b885c6919b49c17d478bd []
621b885c6919b49c17d478be []
621b885c6919b49c17d478bf []
621b885c6919b49c17d478c0 []
621b885c6919b49c17d478c1 []
621b885c6919b49c17d478c2 []
621b885c6919b49c17d478c3 []
621b885c6919b49c17d478c4 []
621b885c6919b49c17d478c5 []
621b885c6919b49c17d478c6 []
621b885c6919b49c17d478c7 []
621b885c6919b49c17d478c8 []
621b885c6919b49c17d478c9 []
621b885c6919b49c17d478ca []
621b885c6919b49c17d478cb []
621b885c6919b49c17d478cc []
621b885c6919b49c17d478cd []
621b885c6919b49c17d478ce []
621b885c6919b49c17d478cf []
621b885c6919b49c17d478d0 []
621b885c6919b49c17d478d1 []
621b885c6919b49c17d478d2 []
621b885c6919b49c17d478d3 []
621b885c6919b49c17d478d4 []
621b885c6919b49c17d478d5 []
621b885c6919b49c17d478d6 []
621b885c6919b49c17d478d7 []
621b885c6919b49c17d478d8 []

621b885c6919b49c17d478d9 []
621b885c6919b49c17d478da []
621b885c6919b49c17d478db []
621b885c6919b49c17d478dc []
621b885c6919b49c17d478dd []
621b885c6919b49c17d478de []
621b885c6919b49c17d478df []
621b885c6919b49c17d478e0 []
621b885c6919b49c17d478e1 []
621b885c6919b49c17d478e2 []
621b885c6919b49c17d478e3 []
621b885c6919b49c17d478e4 []
621b885c6919b49c17d478e5 []
621b885c6919b49c17d478e6 []
621b885c6919b49c17d478e7 []
621b885c6919b49c17d478e8 []
621b885c6919b49c17d478e9 []
621b885c6919b49c17d478ea []
621b885c6919b49c17d478eb []
621b885c6919b49c17d478ec []
621b885c6919b49c17d478ed []
621b885c6919b49c17d478ee []
621b885c6919b49c17d478ef []
621b885c6919b49c17d478f0 []
621b885c6919b49c17d478f1 []
621b885c6919b49c17d478f2 []
621b885c6919b49c17d478f3 []
621b885c6919b49c17d478f4 []
621b885c6919b49c17d478f5 []
621b885c6919b49c17d478f6 []
621b885c6919b49c17d478f7 []
621b885c6919b49c17d478f8 []
621b885c6919b49c17d478f9 []
621b885c6919b49c17d478fa []
621b885c6919b49c17d478fb []
621b885c6919b49c17d478fc []
621b885c6919b49c17d478fd []
621b885c6919b49c17d478fe []
621b885c6919b49c17d478ff []
621b885c6919b49c17d47900 []
621b885c6919b49c17d47901 []
621b885c6919b49c17d47902 []
621b885c6919b49c17d47903 []
621b885c6919b49c17d47904 []
621b885c6919b49c17d47905 []
621b885c6919b49c17d47906 []
621b885c6919b49c17d47907 []
621b885c6919b49c17d47908 []
621b885c6919b49c17d47909 []
621b885c6919b49c17d4790a []
621b885c6919b49c17d4790b []
621b885c6919b49c17d4790c []
621b885c6919b49c17d4790d []
621b885c6919b49c17d4790e []
621b885c6919b49c17d4790f []
621b885c6919b49c17d47910 []
621b885c6919b49c17d47911 []
621b885c6919b49c17d47912 []
621b885c6919b49c17d47913 []
621b885c6919b49c17d47914 []
621b885c6919b49c17d47915 []
621b885c6919b49c17d47916 []
621b885c6919b49c17d47917 []
621b885c6919b49c17d47918 []
621b885c6919b49c17d47919 []
621b885c6919b49c17d4791a []
621b885c6919b49c17d4791b []
621b885c6919b49c17d4791c []
621b885c6919b49c17d4791d []
621b885c6919b49c17d4791e []
621b885c6919b49c17d4791f []
621b885c6919b49c17d47920 []
621b885c6919b49c17d47921 []
621b885c6919b49c17d47922 []
621b885c6919b49c17d47923 []
621b885c6919b49c17d47924 []
621b885c6919b49c17d47925 []
621b885c6919b49c17d47926 []
621b885c6919b49c17d47927 []
621b885c6919b49c17d47928 []
621b885c6919b49c17d47929 []
621b885c6919b49c17d4792a []
621b885c6919b49c17d4792b []
621b885c6919b49c17d4792c []
621b885c6919b49c17d4792d []
621b885c6919b49c17d4792e []
621b885c6919b49c17d4792f []
621b885c6919b49c17d47930 []
621b885c6919b49c17d47931 []
621b885c6919b49c17d47932 []
621b885c6919b49c17d47933 []
621b885c6919b49c17d47934 []
621b885c6919b49c17d47935 []
621b885c6919b49c17d47936 []
621b885c6919b49c17d47937 []
621b885c6919b49c17d47938 []
621b885c6919b49c17d47939 []
621b885c6919b49c17d4793a []
621b885c6919b49c17d4793b []
621b885c6919b49c17d4793c []
621b885c6919b49c17d4793d []
621b885c6919b49c17d4793e []
621b885c6919b49c17d4793f []
621b885c6919b49c17d47940 []
621b885c6919b49c17d47941 []
621b885c6919b49c17d47942 []
621b885c6919b49c17d47943 []
621b885c6919b49c17d47944 []
621b885c6919b49c17d47945 []
621b885c6919b49c17d47946 []
621b885c6919b49c17d47947 []
621b885c6919b49c17d47948 []
621b885c6919b49c17d47949 []
621b885c6919b49c17d4794a []
621b885c6919b49c17d4794b []
621b885c6919b49c17d4794c []
621b885c6919b49c17d4794d []
621b885c6919b49c17d4794e []
621b885c6919b49c17d4794f []
621b885c6919b49c17d47950 []
621b885c6919b49c17d47951 []
621b885c6919b49c17d47952 []
621b885c6919b49c17d47953 []
621b885c6919b49c17d47954 []
621b885c6919b49c17d47955 []
621b885c6919b49c17d47956 []
621b885c6919b49c17d47957 []
621b885c6919b49c17d47958 []
621b885c6919b49c17d47959 []
621b885c6919b49c17d4795a []
621b885c6919b49c17d4795b []
621b885c6919b49c17d4795c []
621b885c6919b49c17d4795d []
621b885c6919b49c17d4795e []
621b885c6919b49c17d4795f []
621b885c6919b49c17d47960 []
621b885c6919b49c17d47961 []
621b885c6919b49c17d47962 []
621b885c6919b49c17d47963 []
621b885c6919b49c17d47964 []
621b885c6919b49c17d47965 []
621b885c6919b49c17d47966 []
621b885c6919b49c17d47967 []
621b885c6919b49c17d47968 []
621b885c6919b49c17d47969 []
621b885c6919b49c17d4796a []
621b885c6919b49c17d4796b []
621b885c6919b49c17d4796c []
621b885c6919b49c17d4796d []
621b885c6919b49c17d4796e []
621b885c6919b49c17d4796f []
621b885c6919b49c17d47970 []
621b885c6919b49c17d47971 []
621b885c6919b49c17d47972 []
621b885c6919b49c17d47973 []
621b885c6919b49c17d47974 []
621b885c6919b49c17d47975 []
621b885c6919b49c17d47976 []
621b885c6919b49c17d47977 []
621b885c6919b49c17d47978 []
621b885c6919b49c17d47979 []
621b885c6919b49c17d4797a []
621b885c6919b49c17d4797b []
621b885c6919b49c17d4797c []
621b885c6919b49c17d4797d []
621b885c6919b49c17d4797e []
621b885c6919b49c17d4797f []
621b885c6919b49c17d47980 []
621b885c6919b49c17d47981 []
621b885c6919b49c17d47982 []
621b885c6919b49c17d47983 []
621b885c6919b49c17d47984 []
621b885c6919b49c17d47985 []
621b885c6919b49c17d47986 []
621b885c6919b49c17d47987 []
621b885c6919b49c17d47988 []
621b885c6919b49c17d47989 []
621b885c6919b49c17d4798a []
621b885c6919b49c17d4798b []
621b885c6919b49c17d4798c []
621b885c6919b49c17d4798d []
621b885c6919b49c17d4798e []
621b885c6919b49c17d4798f []
621b885c6919b49c17d47990 []
621b885c6919b49c17d47991 []
621b885c6919b49c17d47992 []
621b885c6919b49c17d47993 []
621b885c6919b49c17d47994 []
621b885c6919b49c17d47995 []
621b885c6919b49c17d47996 []
621b885c6919b49c17d47997 []
621b885c6919b49c17d47998 []
621b885c6919b49c17d47999 []
621b885c6919b49c17d4799a []
621b885c6919b49c17d4799b []
621b885c6919b49c17d4799c []
621b885c6919b49c17d4799d []
621b885c6919b49c17d4799e []
621b885c6919b49c17d4799f []
621b885c6919b49c17d479a0 []
621b885c6919b49c17d479a1 []
621b885c6919b49c17d479a2 []
621b885c6919b49c17d479a3 []
621b885c6919b49c17d479a4 []
621b885c6919b49c17d479a5 []
621b885c6919b49c17d479a6 []
621b885c6919b49c17d479a7 []
621b885c6919b49c17d479a8 []
621b885c6919b49c17d479a9 []
621b885c6919b49c17d479aa []
621b885c6919b49c17d479ab []
621b885c6919b49c17d479ac []
621b885c6919b49c17d479ad []
621b885c6919b49c17d479ae []
621b885c6919b49c17d479af []
621b885c6919b49c17d479b0 []
621b885c6919b49c17d479b1 []
621b885c6919b49c17d479b2 []
621b885c6919b49c17d479b3 []
621b885c6919b49c17d479b4 []
621b885c6919b49c17d479b5 []
621b885c6919b49c17d479b6 []
621b885c6919b49c17d479b7 []
621b885c6919b49c17d479b8 []
621b885c6919b49c17d479b9 []
621b885c6919b49c17d479ba []
621b885c6919b49c17d479bb []
621b885c6919b49c17d479bc []
621b885c6919b49c17d479bd []
621b885c6919b49c17d479be []
621b885c6919b49c17d479bf []
621b885c6919b49c17d479c0 []
621b885c6919b49c17d479c1 []
621b885c6919b49c17d479c2 []
621b885c6919b49c17d479c3 []
621b885c6919b49c17d479c4 []
621b885c6919b49c17d479c5 []
621b885c6919b49c17d479c6 []
621b885c6919b49c17d479c7 []
621b885c6919b49c17d479c8 []
621b885c6919b49c17d479c9 []
621b885c6919b49c17d479ca []
621b885c6919b49c17d479cb []
621b885c6919b49c17d479cc []
621b885c6919b49c17d479cd []
621b885c6919b49c17d479ce []
621b885c6919b49c17d479cf []
621b885c6919b49c17d479d0 []
621b885c6919b49c17d479d1 []
621b885c6919b49c17d479d2 []
621b885c6919b49c17d479d3 []
621b885c6919b49c17d479d4 []
621b885c6919b49c17d479d5 []
621b885c6919b49c17d479d6 []
621b885c6919b49c17d479d7 []
621b885c6919b49c17d479d8 []
621b885c6919b49c17d479d9 []
621b885c6919b49c17d479da []
621b885c6919b49c17d479db []
621b885c6919b49c17d479dc []
621b885c6919b49c17d479dd []
621b885c6919b49c17d479de []
621b885c6919b49c17d479df []
621b885c6919b49c17d479e0 []
621b885c6919b49c17d479e1 []
621b885c6919b49c17d479e2 []
621b885c6919b49c17d479e3 []
621b885c6919b49c17d479e4 []
621b885c6919b49c17d479e5 []
621b885c6919b49c17d479e6 []
621b885c6919b49c17d479e7 []
621b885c6919b49c17d479e8 []
621b885c6919b49c17d479e9 []
621b885c6919b49c17d479ea []
621b885c6919b49c17d479eb []
621b885c6919b49c17d479ec []
621b885c6919b49c17d479ed []
621b885c6919b49c17d479ee []
621b885c6919b49c17d479ef []
621b885c6919b49c17d479f0 []
621b885c6919b49c17d479f1 []
621b885c6919b49c17d479f2 []
621b885c6919b49c17d479f3 []
621b885c6919b49c17d479f4 []
621b885c6919b49c17d479f5 []
621b885c6919b49c17d479f6 []
621b885c6919b49c17d479f7 []
621b885c6919b49c17d479f8 []
621b885c6919b49c17d479f9 []
621b885c6919b49c17d479fa []
621b885c6919b49c17d479fb []
621b885c6919b49c17d479fc []
621b885c6919b49c17d479fd []

621b885c6919b49c17d479fe []
621b885c6919b49c17d479ff []
621b885c6919b49c17d47a00 []
621b885c6919b49c17d47a01 []
621b885c6919b49c17d47a02 []
621b885c6919b49c17d47a03 []
621b885c6919b49c17d47a04 []
621b885c6919b49c17d47a05 []
621b885c6919b49c17d47a06 []
621b885c6919b49c17d47a07 []
621b885c6919b49c17d47a08 []
621b885c6919b49c17d47a09 []
621b885c6919b49c17d47a0a []
621b885c6919b49c17d47a0b []
621b885c6919b49c17d47a0c []
621b885c6919b49c17d47a0d []
621b885c6919b49c17d47a0e []
621b885c6919b49c17d47a0f []
621b885c6919b49c17d47a10 []
621b885c6919b49c17d47a11 []
621b885c6919b49c17d47a12 []
621b885c6919b49c17d47a13 []
621b885c6919b49c17d47a14 []
621b885c6919b49c17d47a15 []
621b885c6919b49c17d47a16 []
621b885c6919b49c17d47a17 []
621b885c6919b49c17d47a18 []
621b885c6919b49c17d47a19 []
621b885c6919b49c17d47a1a []
621b885c6919b49c17d47a1b []
621b885c6919b49c17d47a1c []
621b885c6919b49c17d47a1d []
621b885c6919b49c17d47a1e []
621b885c6919b49c17d47a1f []
621b885c6919b49c17d47a20 []
621b885c6919b49c17d47a21 []
621b885c6919b49c17d47a22 []
621b885c6919b49c17d47a23 []
621b885c6919b49c17d47a24 []
621b885c6919b49c17d47a25 []
621b885c6919b49c17d47a26 []
621b885c6919b49c17d47a27 []
621b885c6919b49c17d47a28 []
621b885c6919b49c17d47a29 []
621b885c6919b49c17d47a2a []
621b885c6919b49c17d47a2b []
621b885c6919b49c17d47a2c []
621b885c6919b49c17d47a2d []
621b885c6919b49c17d47a2e []
621b885c6919b49c17d47a2f []
621b885c6919b49c17d47a30 []
621b885c6919b49c17d47a31 []
621b885c6919b49c17d47a32 []
621b885c6919b49c17d47a33 []
621b885c6919b49c17d47a34 []
621b885c6919b49c17d47a35 []
621b885c6919b49c17d47a36 []
621b885c6919b49c17d47a37 []
621b885c6919b49c17d47a38 []
621b885c6919b49c17d47a39 []
621b885c6919b49c17d47a3a []
621b885c6919b49c17d47a3b []
621b885c6919b49c17d47a3c []
621b885c6919b49c17d47a3d []
621b885c6919b49c17d47a3e []
621b885c6919b49c17d47a3f []
621b885c6919b49c17d47a40 []
621b885c6919b49c17d47a41 []
621b885c6919b49c17d47a42 []
621b885c6919b49c17d47a43 []
621b885c6919b49c17d47a44 []
621b885c6919b49c17d47a45 []
621b885c6919b49c17d47a46 []
621b885c6919b49c17d47a47 []
621b885c6919b49c17d47a48 []
621b885c6919b49c17d47a49 []
621b885c6919b49c17d47a4a []
621b885c6919b49c17d47a4b []
621b885c6919b49c17d47a4c []
621b885c6919b49c17d47a4d []
621b885c6919b49c17d47a4e []
621b885c6919b49c17d47a4f []
621b885c6919b49c17d47a50 []
621b885c6919b49c17d47a51 []
621b885c6919b49c17d47a52 []
621b885c6919b49c17d47a53 []
621b885c6919b49c17d47a54 []
621b885c6919b49c17d47a55 []
621b885c6919b49c17d47a56 []
621b885c6919b49c17d47a57 []
621b885c6919b49c17d47a58 []
621b885c6919b49c17d47a59 []
621b885c6919b49c17d47a5a []
621b885c6919b49c17d47a5b []
621b885c6919b49c17d47a5c []
621b885c6919b49c17d47a5d []
621b885c6919b49c17d47a5e []
621b885c6919b49c17d47a5f []
621b885c6919b49c17d47a60 []
621b885c6919b49c17d47a61 []
621b885c6919b49c17d47a62 []
621b885c6919b49c17d47a63 []
621b885c6919b49c17d47a64 []
621b885c6919b49c17d47a65 []
621b885c6919b49c17d47a66 []
621b885c6919b49c17d47a67 []
621b885c6919b49c17d47a68 []
621b885c6919b49c17d47a69 []
621b885c6919b49c17d47a6a []
621b885c6919b49c17d47a6b []
621b885c6919b49c17d47a6c []
621b885c6919b49c17d47a6d []
621b885c6919b49c17d47a6e []
621b885c6919b49c17d47a6f []
621b885c6919b49c17d47a70 []
621b885c6919b49c17d47a71 []
621b885c6919b49c17d47a72 []
621b885c6919b49c17d47a73 []
621b885c6919b49c17d47a74 []
621b885c6919b49c17d47a75 []
621b885c6919b49c17d47a76 []
621b885c6919b49c17d47a77 []
621b885c6919b49c17d47a78 []
621b885c6919b49c17d47a79 []
621b885c6919b49c17d47a7a []
621b885c6919b49c17d47a7b []
621b885c6919b49c17d47a7c []
621b885c6919b49c17d47a7d []
621b885c6919b49c17d47a7e []
621b885c6919b49c17d47a7f []
621b885c6919b49c17d47a80 []
621b885c6919b49c17d47a81 []
621b885c6919b49c17d47a82 []
621b885c6919b49c17d47a83 []
621b885c6919b49c17d47a84 []
621b885c6919b49c17d47a85 []
621b885c6919b49c17d47a86 []
621b885c6919b49c17d47a87 []
621b885c6919b49c17d47a88 []
621b885c6919b49c17d47a89 []
621b885c6919b49c17d47a8a []
621b885c6919b49c17d47a8b []
621b885c6919b49c17d47a8c []
621b885c6919b49c17d47a8d []
621b885c6919b49c17d47a8e []
621b885c6919b49c17d47a8f []
621b885c6919b49c17d47a90 []
621b885c6919b49c17d47a91 []
621b885c6919b49c17d47a92 []
621b885c6919b49c17d47a93 []
621b885c6919b49c17d47a94 []
621b885c6919b49c17d47a95 []
621b885c6919b49c17d47a96 []
621b885c6919b49c17d47a97 []
621b885c6919b49c17d47a98 []
621b885c6919b49c17d47a99 []
621b885c6919b49c17d47a9a []
621b885c6919b49c17d47a9b []
621b885c6919b49c17d47a9c []
621b885c6919b49c17d47a9d []
621b885c6919b49c17d47a9e []
621b885c6919b49c17d47a9f []
621b885c6919b49c17d47aa0 []
621b885c6919b49c17d47aa1 []
621b885c6919b49c17d47aa2 []
621b885c6919b49c17d47aa3 []
621b885c6919b49c17d47aa4 []
621b885c6919b49c17d47aa5 []
621b885c6919b49c17d47aa6 []
621b885c6919b49c17d47aa7 []
621b885c6919b49c17d47aa8 []
621b885c6919b49c17d47aa9 []
621b885c6919b49c17d47aaa []
621b885c6919b49c17d47aab []
621b885c6919b49c17d47aac []
621b885c6919b49c17d47aad []
621b885c6919b49c17d47aae []
621b885c6919b49c17d47aaf []
621b885c6919b49c17d47ab0 []
621b885c6919b49c17d47ab1 []
621b885c6919b49c17d47ab2 []
621b885c6919b49c17d47ab3 []
621b885c6919b49c17d47ab4 []
621b885c6919b49c17d47ab5 []
621b885c6919b49c17d47ab6 []
621b885c6919b49c17d47ab7 []
621b885c6919b49c17d47ab8 []
621b885c6919b49c17d47ab9 []
621b885c6919b49c17d47aba []
621b885c6919b49c17d47abb []
621b885c6919b49c17d47abc []
621b885c6919b49c17d47abd []
621b885c6919b49c17d47abe []
621b885c6919b49c17d47abf []
621b885c6919b49c17d47ac0 []
621b885c6919b49c17d47ac1 []
621b885c6919b49c17d47ac2 []
621b885c6919b49c17d47ac3 []
621b885c6919b49c17d47ac4 []
621b885c6919b49c17d47ac5 []
621b885c6919b49c17d47ac6 []
621b885c6919b49c17d47ac7 []
621b885c6919b49c17d47ac8 []
621b885c6919b49c17d47ac9 []
621b885c6919b49c17d47aca []
621b885c6919b49c17d47acb []
621b885c6919b49c17d47acc []
621b885c6919b49c17d47acd []
621b885c6919b49c17d47ace []
621b885c6919b49c17d47acf []
621b885c6919b49c17d47ad0 []
621b885c6919b49c17d47ad1 []
621b885c6919b49c17d47ad2 []
621b885c6919b49c17d47ad3 []
621b885c6919b49c17d47ad4 []
621b885c6919b49c17d47ad5 []
621b885c6919b49c17d47ad6 []
621b885c6919b49c17d47ad7 []
621b885c6919b49c17d47ad8 []
621b885c6919b49c17d47ad9 []
621b885c6919b49c17d47ada []
621b885c6919b49c17d47adb []
621b885c6919b49c17d47adc []
621b885c6919b49c17d47add []
621b885c6919b49c17d47ade []
621b885c6919b49c17d47adf []
621b885c6919b49c17d47ae0 []
621b885c6919b49c17d47ae1 []
621b885c6919b49c17d47ae2 []
621b885c6919b49c17d47ae3 []
621b885c6919b49c17d47ae4 []
621b885c6919b49c17d47ae5 []
621b885c6919b49c17d47ae6 []
621b885c6919b49c17d47ae7 []
621b885c6919b49c17d47ae8 []

In [194]:
# Modification des features liés à la Synopsis dans la BDD mongo
for doc in collec.find():
    txt = doc['Synopsis']
    
    Data_Analyst = get_Data_Analyst(txt)
    Data_Scientist = get_Data_Scientist(txt)
    Developpeur =get_Developpeur(txt)
    Business_Intelligence = get_Business_Intelligence(txt)
    
    Consultant = get_Consultant(txt)
    Senior = get_Senior(txt)
    Debutant = get_word_Debutant(txt)
    Cadre = get_Cadre(txt)
    
    word_Engineer = get_word_Engineer(txt)
    big_data = get_big_data(txt)
    word_NLP = get_word_NLP(txt)
    
    word_CDI = get_word_CDI(txt)
    word_CDD = get_word_CDD(txt)
    word_freelance = get_word_freelance(txt)
    
    BacPlus5 = get_BacPlus5(txt)
    BacPlus4 = get_BacPlus4(txt)
    BacPlus3 = get_BacPlus3(txt)
    BacPlus2 = get_BacPlus2(txt)
    
    Python = get_word_Python(txt)
    Pyspark = get_word_Pyspark(txt)
    Java = get_word_Java(txt)
    Julia = get_word_Julia(txt)
    JavaScript = get_word_JavaScript(txt)
    PHP = get_word_PHP(txt)
    CPlusPlus = get_CPlusPlus(txt)
    SQL = get_SQL(txt)
    NoSQL = get_NoSQL(txt)
    AWS = get_word_AWS(txt)
    Azure = get_word_Azure(txt)
    Kafka = get_Kafka(txt)
    SQL_Server = get_SQL_Server(txt)
    machine_learning = get_machine_learning(txt)
    deep_learning = get_deep_learning(txt)
    English = get_English(txt)
    
    id = doc['_id']

    print(id, word_CDI)

    # Les lignes suivantes doivent être décochées en tant que commentaire 
    # afin de charger les nouvelles features dans la nouvelle collection        

    #collec.update_one({'_id': id}, {"$set": {"Data Analyst": len(Data_Analyst)}})
    #collec.update_one({'_id': id}, {"$set": {"Data Scientist": len(Data_Scientist)}})
    #collec.update_one({'_id': id}, {"$set": {"Developpeur": len(Developpeur)}})
    #collec.update_one({'_id': id}, {"$set": {"Business Intelligence": len(Business_Intelligence)}})    
    #collec.update_one({'_id': id}, {"$set": {"Consultant": len(Consultant)}})
    #collec.update_one({'_id': id}, {"$set": {"Senior": len(Senior)}})
    #collec.update_one({'_id': id}, {"$set": {"Debutant": len(Debutant)}})
    #collec.update_one({'_id': id}, {"$set": {"Cadre": len(Cadre)}})
    
    #collec.update_one({'_id': id}, {"$set": {"Engineer": len(word_Engineer)}})
    #collec.update_one({'_id': id}, {"$set": {"big data": len(big_data)}})
    #collec.update_one({'_id': id}, {"$set": {"NLP": len(word_NLP)}})
    #collec.update_one({'_id': id}, {"$set": {"CDI": len(word_CDI)}})
    #collec.update_one({'_id': id}, {"$set": {"CDD": len(word_CDD)}})
    #collec.update_one({'_id': id}, {"$set": {"freelance": len(word_freelance)}})
    
    #collec.update_one({'_id': id}, {"$set": {"Bac+5": len(BacPlus5)}})
    #collec.update_one({'_id': id}, {"$set": {"Bac+4": len(BacPlus4)}})
    #collec.update_one({'_id': id}, {"$set": {"Bac+3": len(BacPlus3)}})
    #collec.update_one({'_id': id}, {"$set": {"Bac+2": len(BacPlus2)}})
    
    #collec.update_one({'_id': id}, {"$set": {"Python": len(Python)}})
    #collec.update_one({'_id': id}, {"$set": {"Pyspark": len(Pyspark)}})
    #collec.update_one({'_id': id}, {"$set": {"Java": len(Java)}})
    #collec.update_one({'_id': id}, {"$set": {"Julia": len(Julia)}})
    #collec.update_one({'_id': id}, {"$set": {"JavaScript": len(JavaScript)}})
    #collec.update_one({'_id': id}, {"$set": {"PHP": len(PHP)}})
    #collec.update_one({'_id': id}, {"$set": {"C++": len(CPlusPlus)}})
    #collec.update_one({'_id': id}, {"$set": {"SQL": len(SQL)}})
    #collec.update_one({'_id': id}, {"$set": {"NoSQL": len(NoSQL)}})        
    #collec.update_one({'_id': id}, {"$set": {"AWS": len(AWS)}})
    #collec.update_one({'_id': id}, {"$set": {"Azure": len(Azure)}})
    #collec.update_one({'_id': id}, {"$set": {"Kafka": len(Kafka)}})
    #collec.update_one({'_id': id}, {"$set": {"SQL Server": len(SQL_Server)}})
    #collec.update_one({'_id': id}, {"$set": {"Machine_learning": len(machine_learning)}})
    #collec.update_one({'_id': id}, {"$set": {"deep_learning": len(deep_learning)}})
    #"collec.update_one({'_id': id}, {"$set": {"English": len(English)}})

621b885c6919b49c17d477b3 ['CDI']
621b885c6919b49c17d477b4 []
621b885c6919b49c17d477b5 []
621b885c6919b49c17d477b6 []
621b885c6919b49c17d477b7 []
621b885c6919b49c17d477b8 ['CDI']
621b885c6919b49c17d477b9 ['CDI']
621b885c6919b49c17d477ba ['CDI']
621b885c6919b49c17d477bb []
621b885c6919b49c17d477bc ['CDI']
621b885c6919b49c17d477bd []
621b885c6919b49c17d477be []
621b885c6919b49c17d477bf []
621b885c6919b49c17d477c0 []
621b885c6919b49c17d477c1 ['CDI', 'CDI']
621b885c6919b49c17d477c2 ['CDI', 'CDI']
621b885c6919b49c17d477c3 ['CDI']
621b885c6919b49c17d477c4 ['CDI']
621b885c6919b49c17d477c5 ['CDI']
621b885c6919b49c17d477c6 ['CDI']
621b885c6919b49c17d477c7 ['CDI', 'CDI']
621b885c6919b49c17d477c8 ['CDI', 'CDI', 'CDI', 'CDI']
621b885c6919b49c17d477c9 ['CDI']
621b885c6919b49c17d477ca ['CDI']
621b885c6919b49c17d477cb []
621b885c6919b49c17d477cc ['CDI']
621b885c6919b49c17d477cd []
621b885c6919b49c17d477ce ['CDI', 'CDI']
621b885c6919b49c17d477cf []
621b885c6919b49c17d477d0 []
621b885c6919b49c17d477d1 []
621b885c6919b49c17d477d2 []
621b885c6919b49c17d477d3 []
621b885c6919b49c17d477d4 ['CDI']
621b885c6919b49c17d477d5 ['CDI']
621b885c6919b49c17d477d6 ['CDI']
621b885c6919b49c17d477d7 ['CDI']
621b885c6919b49c17d477d8 ['CDI']
621b885c6919b49c17d477d9 ['CDI']
621b885c6919b49c17d477da []
621b885c6919b49c17d477db ['CDI']
621b885c6919b49c17d477dc ['CDI', 'CDI']
621b885c6919b49c17d477dd ['CDI']
621b885c6919b49c17d477de ['CDI']
621b885c6919b49c17d477df ['CDI']
621b885c6919b49c17d477e0 ['CDI']
621b885c6919b49c17d477e1 []
621b885c6919b49c17d477e2 ['CDI']
621b885c6919b49c17d477e3 ['CDI']
621b885c6919b49c17d477e4 ['CDI']
621b885c6919b49c17d477e5 ['CDI']
621b885c6919b49c17d477e6 ['CDI']
621b885c6919b49c17d477e7 []
621b885c6919b49c17d477e8 ['CDI']
621b885c6919b49c17d477e9 ['CDI']
621b885c6919b49c17d477ea ['CDI']
621b885c6919b49c17d477eb ['CDI']
621b885c6919b49c17d477ec []
621b885c6919b49c17d477ed ['CDI', 'CDI']
621b885c6919b49c17d477ee ['CDI']
621b885c6919b49c17d477ef ['CDI']
621b885c6919b49c17d477f0 ['CDI']
621b885c6919b49c17d477f1 ['CDI']
621b885c6919b49c17d477f2 ['CDI', 'CDI']
621b885c6919b49c17d477f3 ['CDI']
621b885c6919b49c17d477f4 []
621b885c6919b49c17d477f5 []
621b885c6919b49c17d477f6 []
621b885c6919b49c17d477f7 []
621b885c6919b49c17d477f8 ['CDI']
621b885c6919b49c17d477f9 ['CDI']
621b885c6919b49c17d477fa []
621b885c6919b49c17d477fb []
621b885c6919b49c17d477fc ['CDI']
621b885c6919b49c17d477fd ['CDI']
621b885c6919b49c17d477fe ['CDI']
621b885c6919b49c17d477ff ['CDI', 'CDI']
621b885c6919b49c17d47800 []
621b885c6919b49c17d47801 ['CDI', 'CDI']
621b885c6919b49c17d47802 ['CDI']
621b885c6919b49c17d47803 ['CDI']
621b885c6919b49c17d47804 ['CDI']
621b885c6919b49c17d47805 ['CDI']
621b885c6919b49c17d47806 ['CDI', 'CDI']
621b885c6919b49c17d47807 ['CDI', 'CDI']
621b885c6919b49c17d47808 ['CDI']
621b885c6919b49c17d47809 ['CDI']
621b885c6919b49c17d4780a []
621b885c6919b49c17d4780b ['CDI']
621b885c6919b49c17d4780c ['CDI']
621b885c6919b49c17d4780d ['CDI', 'CDI']
621b885c6919b49c17d4780e ['CDI']
621b885c6919b49c17d4780f ['CDI']
621b885c6919b49c17d47810 ['CDI']
621b885c6919b49c17d47811 ['CDI', 'CDI']
621b885c6919b49c17d47812 ['CDI']
621b885c6919b49c17d47813 ['CDI']
621b885c6919b49c17d47814 ['CDI', 'CDI']
621b885c6919b49c17d47815 ['CDI']
621b885c6919b49c17d47816 ['CDI']
621b885c6919b49c17d47817 ['CDI']
621b885c6919b49c17d47818 ['CDI']
621b885c6919b49c17d47819 ['CDI']
621b885c6919b49c17d4781a []
621b885c6919b49c17d4781b ['CDI']
621b885c6919b49c17d4781c ['CDI']
621b885c6919b49c17d4781d []
621b885c6919b49c17d4781e ['CDI', 'CDI']
621b885c6919b49c17d4781f []
621b885c6919b49c17d47820 ['CDI', 'CDI']
621b885c6919b49c17d47821 []
621b885c6919b49c17d47822 ['CDI']
621b885c6919b49c17d47823 ['CDI']
621b885c6919b49c17d47824 []
621b885c6919b49c17d47825 ['CDI']
621b885c6919b49c17d47826 ['CDI', 'CDI']
621b885c6919b49c17d47827 ['CDI']
621b885c6919b49c17d47828 ['CDI']
621b885c6919b49c17d47829 ['CDI']
621b885c6919b49c17d4782a ['CDI']
621b885c6919b49c17d4782b ['CDI']
621b885c6919b49c17d4782c ['CDI']
621b885c6919b49c17d4782d []
621b885c6919b49c17d4782e ['CDI']
621b885c6919b49c17d4782f ['CDI']
621b885c6919b49c17d47830 ['CDI']
621b885c6919b49c17d47831 ['CDI']
621b885c6919b49c17d47832 []
621b885c6919b49c17d47833 ['CDI']
621b885c6919b49c17d47834 ['CDI']
621b885c6919b49c17d47835 ['CDI']
621b885c6919b49c17d47836 ['CDI']
621b885c6919b49c17d47837 ['CDI']
621b885c6919b49c17d47838 ['CDI']
621b885c6919b49c17d47839 ['CDI']
621b885c6919b49c17d4783a ['CDI']
621b885c6919b49c17d4783b []
621b885c6919b49c17d4783c ['CDI']
621b885c6919b49c17d4783d ['CDI']
621b885c6919b49c17d4783e ['CDI']
621b885c6919b49c17d4783f ['CDI']
621b885c6919b49c17d47840 ['CDI']
621b885c6919b49c17d47841 ['CDI']
621b885c6919b49c17d47842 ['CDI', 'CDI']
621b885c6919b49c17d47843 ['CDI']
621b885c6919b49c17d47844 ['CDI', 'CDI']
621b885c6919b49c17d47845 ['CDI']
621b885c6919b49c17d47846 ['CDI', 'CDI']
621b885c6919b49c17d47847 ['CDI']
621b885c6919b49c17d47848 ['CDI']
621b885c6919b49c17d47849 ['CDI']
621b885c6919b49c17d4784a ['CDI']
621b885c6919b49c17d4784b ['CDI']
621b885c6919b49c17d4784c ['CDI']
621b885c6919b49c17d4784d ['CDI']
621b885c6919b49c17d4784e ['CDI']
621b885c6919b49c17d4784f ['CDI']
621b885c6919b49c17d47850 ['CDI', 'CDI', 'CDI']
621b885c6919b49c17d47851 ['CDI', 'CDI', 'CDI']
621b885c6919b49c17d47852 []
621b885c6919b49c17d47853 []
621b885c6919b49c17d47854 ['CDI']
621b885c6919b49c17d47855 ['CDI', 'CDI']
621b885c6919b49c17d47856 ['CDI', 'CDI']
621b885c6919b49c17d47857 ['CDI', 'CDI']
621b885c6919b49c17d47858 ['CDI']
621b885c6919b49c17d47859 []
621b885c6919b49c17d4785a ['CDI']
621b885c6919b49c17d4785b ['CDI']
621b885c6919b49c17d4785c []
621b885c6919b49c17d4785d ['CDI', 'CDI']
621b885c6919b49c17d4785e ['CDI']
621b885c6919b49c17d4785f ['CDI', 'CDI']
621b885c6919b49c17d47860 ['CDI', 'CDI']
621b885c6919b49c17d47861 []
621b885c6919b49c17d47862 ['CDI']
621b885c6919b49c17d47863 ['CDI', 'CDI']
621b885c6919b49c17d47864 []
621b885c6919b49c17d47865 []
621b885c6919b49c17d47866 ['CDI']
621b885c6919b49c17d47867 ['CDI']
621b885c6919b49c17d47868 []
621b885c6919b49c17d47869 []
621b885c6919b49c17d4786a ['CDI']
621b885c6919b49c17d4786b ['CDI']
621b885c6919b49c17d4786c ['CDI', 'CDI']
621b885c6919b49c17d4786d []
621b885c6919b49c17d4786e []
621b885c6919b49c17d4786f ['CDI']
621b885c6919b49c17d47870 ['CDI', 'CDI']
621b885c6919b49c17d47871 ['CDI']
621b885c6919b49c17d47872 ['CDI']
621b885c6919b49c17d47873 ['CDI']
621b885c6919b49c17d47874 ['CDI']
621b885c6919b49c17d47875 []
621b885c6919b49c17d47876 []
621b885c6919b49c17d47877 []
621b885c6919b49c17d47878 []
621b885c6919b49c17d47879 []
621b885c6919b49c17d4787a []
621b885c6919b49c17d4787b []
621b885c6919b49c17d4787c ['CDI']
621b885c6919b49c17d4787d []
621b885c6919b49c17d4787e ['CDI']
621b885c6919b49c17d4787f ['CDI']
621b885c6919b49c17d47880 ['CDI']
621b885c6919b49c17d47881 ['CDI']
621b885c6919b49c17d47882 ['CDI']
621b885c6919b49c17d47883 ['CDI']
621b885c6919b49c17d47884 ['CDI']
621b885c6919b49c17d47885 ['CDI']
621b885c6919b49c17d47886 ['CDI']
621b885c6919b49c17d47887 ['CDI']
621b885c6919b49c17d47888 ['CDI']
621b885c6919b49c17d47889 ['CDI', 'CDI']
621b885c6919b49c17d4788a ['CDI', 'CDI']
621b885c6919b49c17d4788b ['CDI']
621b885c6919b49c17d4788c ['CDI']
621b885c6919b49c17d4788d ['CDI']
621b885c6919b49c17d4788e []
621b885c6919b49c17d4788f []
621b885c6919b49c17d47890 ['CDI']
621b885c6919b49c17d47891 []
621b885c6919b49c17d47892 ['CDI']
621b885c6919b49c17d47893 ['CDI']
621b885c6919b49c17d47894 ['CDI']
621b885c6919b49c17d47895 ['CDI']
621b885c6919b49c17d47896 ['CDI']
621b885c6919b49c17d47897 ['CDI']
621b885c6919b49c17d47898 []
621b885c6919b49c17d47899 []
621b885c6919b49c17d4789a ['CDI']
621b885c6919b49c17d4789b ['CDI']
621b885c6919b49c17d4789c ['CDI']
621b885c6919b49c17d4789d ['CDI']
621b885c6919b49c17d4789e ['CDI']
621b885c6919b49c17d4789f ['CDI']
621b885c6919b49c17d478a0 ['CDI']
621b885c6919b49c17d478a1 ['CDI']
621b885c6919b49c17d478a2 ['CDI']
621b885c6919b49c17d478a3 ['CDI']
621b885c6919b49c17d478a4 ['CDI']
621b885c6919b49c17d478a5 ['CDI']
621b885c6919b49c17d478a6 ['CDI', 'CDI']
621b885c6919b49c17d478a7 ['CDI']
621b885c6919b49c17d478a8 ['CDI']
621b885c6919b49c17d478a9 []
621b885c6919b49c17d478aa []
621b885c6919b49c17d478ab ['CDI']
621b885c6919b49c17d478ac []

621b885c6919b49c17d478ad ['CDI']
621b885c6919b49c17d478ae []
621b885c6919b49c17d478af ['CDI']
621b885c6919b49c17d478b0 ['CDI']
621b885c6919b49c17d478b1 ['CDI']
621b885c6919b49c17d478b2 ['CDI']
621b885c6919b49c17d478b3 ['CDI', 'CDI']
621b885c6919b49c17d478b4 []
621b885c6919b49c17d478b5 ['CDI']
621b885c6919b49c17d478b6 []
621b885c6919b49c17d478b7 []
621b885c6919b49c17d478b8 ['CDI']
621b885c6919b49c17d478b9 ['CDI']
621b885c6919b49c17d478ba []
621b885c6919b49c17d478bb ['CDI']
621b885c6919b49c17d478bc ['CDI', 'CDI']
621b885c6919b49c17d478bd ['CDI', 'CDI']
621b885c6919b49c17d478be ['CDI']
621b885c6919b49c17d478bf ['CDI', 'CDI']
621b885c6919b49c17d478c0 []
621b885c6919b49c17d478c1 ['CDI']
621b885c6919b49c17d478c2 ['CDI', 'CDI']
621b885c6919b49c17d478c3 ['CDI']
621b885c6919b49c17d478c4 ['CDI']
621b885c6919b49c17d478c5 ['CDI']
621b885c6919b49c17d478c6 ['CDI']
621b885c6919b49c17d478c7 ['CDI']
621b885c6919b49c17d478c8 ['CDI']
621b885c6919b49c17d478c9 []
621b885c6919b49c17d478ca []
621b885c6919b49c17d478cb ['CDI', 'CDI']
621b885c6919b49c17d478cc ['CDI', 'CDI']
621b885c6919b49c17d478cd ['CDI']
621b885c6919b49c17d478ce ['CDI']
621b885c6919b49c17d478cf ['CDI']
621b885c6919b49c17d478d0 []
621b885c6919b49c17d478d1 ['CDI']
621b885c6919b49c17d478d2 ['CDI', 'CDI']
621b885c6919b49c17d478d3 ['CDI']
621b885c6919b49c17d478d4 ['CDI']
621b885c6919b49c17d478d5 ['CDI']
621b885c6919b49c17d478d6 ['CDI']
621b885c6919b49c17d478d7 []
621b885c6919b49c17d478d8 []
621b885c6919b49c17d478d9 ['CDI']
621b885c6919b49c17d478da ['CDI']
621b885c6919b49c17d478db ['CDI']
621b885c6919b49c17d478dc ['CDI']
621b885c6919b49c17d478dd ['CDI']
621b885c6919b49c17d478de []
621b885c6919b49c17d478df ['CDI']
621b885c6919b49c17d478e0 []
621b885c6919b49c17d478e1 ['CDI']
621b885c6919b49c17d478e2 ['CDI', 'CDI']
621b885c6919b49c17d478e3 ['CDI']
621b885c6919b49c17d478e4 ['CDI']
621b885c6919b49c17d478e5 ['CDI']
621b885c6919b49c17d478e6 ['CDI']
621b885c6919b49c17d478e7 ['CDI', 'CDI']
621b885c6919b49c17d478e8 ['CDI', 'CDI']
621b885c6919b49c17d478e9 ['CDI']
621b885c6919b49c17d478ea ['CDI']
621b885c6919b49c17d478eb ['CDI', 'CDI']
621b885c6919b49c17d478ec ['CDI']
621b885c6919b49c17d478ed ['CDI']
621b885c6919b49c17d478ee ['CDI']
621b885c6919b49c17d478ef ['CDI']
621b885c6919b49c17d478f0 []
621b885c6919b49c17d478f1 []
621b885c6919b49c17d478f2 ['CDI']
621b885c6919b49c17d478f3 ['CDI']
621b885c6919b49c17d478f4 ['CDI']
621b885c6919b49c17d478f5 ['CDI']
621b885c6919b49c17d478f6 []
621b885c6919b49c17d478f7 []
621b885c6919b49c17d478f8 ['CDI']
621b885c6919b49c17d478f9 ['CDI', 'CDI']
621b885c6919b49c17d478fa ['CDI']
621b885c6919b49c17d478fb ['CDI']
621b885c6919b49c17d478fc ['CDI']
621b885c6919b49c17d478fd ['CDI', 'CDI']
621b885c6919b49c17d478fe ['CDI', 'CDI']
621b885c6919b49c17d478ff ['CDI', 'CDI']
621b885c6919b49c17d47900 []
621b885c6919b49c17d47901 []
621b885c6919b49c17d47902 ['CDI']
621b885c6919b49c17d47903 ['CDI']
621b885c6919b49c17d47904 ['CDI', 'CDI']
621b885c6919b49c17d47905 ['CDI']
621b885c6919b49c17d47906 ['CDI']
621b885c6919b49c17d47907 []
621b885c6919b49c17d47908 []
621b885c6919b49c17d47909 ['CDI']
621b885c6919b49c17d4790a []
621b885c6919b49c17d4790b ['CDI', 'CDI']
621b885c6919b49c17d4790c ['CDI']
621b885c6919b49c17d4790d []
621b885c6919b49c17d4790e []
621b885c6919b49c17d4790f []
621b885c6919b49c17d47910 ['CDI', 'CDI', 'CDI']
621b885c6919b49c17d47911 []
621b885c6919b49c17d47912 []
621b885c6919b49c17d47913 ['CDI', 'CDI']
621b885c6919b49c17d47914 ['CDI', 'CDI']
621b885c6919b49c17d47915 []
621b885c6919b49c17d47916 []
621b885c6919b49c17d47917 []
621b885c6919b49c17d47918 ['CDI', 'CDI']
621b885c6919b49c17d47919 ['CDI', 'CDI']
621b885c6919b49c17d4791a []
621b885c6919b49c17d4791b []
621b885c6919b49c17d4791c ['CDI']
621b885c6919b49c17d4791d ['CDI']
621b885c6919b49c17d4791e []
621b885c6919b49c17d4791f []
621b885c6919b49c17d47920 []
621b885c6919b49c17d47921 ['Cdi']
621b885c6919b49c17d47922 ['CDI']
621b885c6919b49c17d47923 []
621b885c6919b49c17d47924 []
621b885c6919b49c17d47925 []
621b885c6919b49c17d47926 ['CDI']
621b885c6919b49c17d47927 []
621b885c6919b49c17d47928 []
621b885c6919b49c17d47929 []
621b885c6919b49c17d4792a []
621b885c6919b49c17d4792b []
621b885c6919b49c17d4792c []
621b885c6919b49c17d4792d ['CDI', 'CDI']
621b885c6919b49c17d4792e ['CDI', 'CDI']
621b885c6919b49c17d4792f []
621b885c6919b49c17d47930 []
621b885c6919b49c17d47931 []
621b885c6919b49c17d47932 ['CDI', 'CDI']
621b885c6919b49c17d47933 ['CDI', 'CDI']
621b885c6919b49c17d47934 []
621b885c6919b49c17d47935 []
621b885c6919b49c17d47936 ['CDI']
621b885c6919b49c17d47937 []
621b885c6919b49c17d47938 ['CDI']
621b885c6919b49c17d47939 ['CDI']
621b885c6919b49c17d4793a []
621b885c6919b49c17d4793b []
621b885c6919b49c17d4793c ['CDI']
621b885c6919b49c17d4793d []
621b885c6919b49c17d4793e []
621b885c6919b49c17d4793f []
621b885c6919b49c17d47940 ['CDI']
621b885c6919b49c17d47941 ['CDI']
621b885c6919b49c17d47942 []
621b885c6919b49c17d47943 []
621b885c6919b49c17d47944 []
621b885c6919b49c17d47945 []
621b885c6919b49c17d47946 []
621b885c6919b49c17d47947 []
621b885c6919b49c17d47948 []
621b885c6919b49c17d47949 []
621b885c6919b49c17d4794a ['CDI']
621b885c6919b49c17d4794b ['CDI']
621b885c6919b49c17d4794c ['CDI', 'CDI']
621b885c6919b49c17d4794d []
621b885c6919b49c17d4794e ['CDI']
621b885c6919b49c17d4794f ['CDI']
621b885c6919b49c17d47950 ['CDI']
621b885c6919b49c17d47951 ['CDI']
621b885c6919b49c17d47952 []
621b885c6919b49c17d47953 []
621b885c6919b49c17d47954 []
621b885c6919b49c17d47955 []
621b885c6919b49c17d47956 []
621b885c6919b49c17d47957 []
621b885c6919b49c17d47958 []
621b885c6919b49c17d47959 []
621b885c6919b49c17d4795a []
621b885c6919b49c17d4795b []
621b885c6919b49c17d4795c []
621b885c6919b49c17d4795d []
621b885c6919b49c17d4795e []
621b885c6919b49c17d4795f []
621b885c6919b49c17d47960 []
621b885c6919b49c17d47961 ['CDI']
621b885c6919b49c17d47962 ['CDI']
621b885c6919b49c17d47963 []
621b885c6919b49c17d47964 []
621b885c6919b49c17d47965 []
621b885c6919b49c17d47966 []
621b885c6919b49c17d47967 []
621b885c6919b49c17d47968 []
621b885c6919b49c17d47969 []
621b885c6919b49c17d4796a []
621b885c6919b49c17d4796b []
621b885c6919b49c17d4796c ['CDI']
621b885c6919b49c17d4796d ['CDI']
621b885c6919b49c17d4796e []
621b885c6919b49c17d4796f []
621b885c6919b49c17d47970 []
621b885c6919b49c17d47971 []
621b885c6919b49c17d47972 ['CDI', 'CDI']
621b885c6919b49c17d47973 ['CDI', 'CDI']
621b885c6919b49c17d47974 ['CDI', 'CDI']
621b885c6919b49c17d47975 []
621b885c6919b49c17d47976 ['CDI']
621b885c6919b49c17d47977 ['CDI']
621b885c6919b49c17d47978 ['CDI', 'CDI']
621b885c6919b49c17d47979 ['CDI', 'CDI', 'CDI', 'CDI']
621b885c6919b49c17d4797a ['CDI']
621b885c6919b49c17d4797b []
621b885c6919b49c17d4797c []
621b885c6919b49c17d4797d []
621b885c6919b49c17d4797e []
621b885c6919b49c17d4797f []
621b885c6919b49c17d47980 []
621b885c6919b49c17d47981 []
621b885c6919b49c17d47982 ['CDI']
621b885c6919b49c17d47983 ['CDI']
621b885c6919b49c17d47984 []
621b885c6919b49c17d47985 []
621b885c6919b49c17d47986 ['CDI', 'CDI']
621b885c6919b49c17d47987 []
621b885c6919b49c17d47988 []
621b885c6919b49c17d47989 []
621b885c6919b49c17d4798a []
621b885c6919b49c17d4798b ['CDI']
621b885c6919b49c17d4798c []
621b885c6919b49c17d4798d ['CDI', 'CDI']
621b885c6919b49c17d4798e ['CDI']
621b885c6919b49c17d4798f []
621b885c6919b49c17d47990 ['CDI', 'CDI']
621b885c6919b49c17d47991 ['CDI', 'CDI']
621b885c6919b49c17d47992 ['CDI', 'CDI']
621b885c6919b49c17d47993 ['CDI', 'CDI']
621b885c6919b49c17d47994 ['CDI']
621b885c6919b49c17d47995 ['CDI']
621b885c6919b49c17d47996 []
621b885c6919b49c17d47997 ['CDI']
621b885c6919b49c17d47998 ['CDI']
621b885c6919b49c17d47999 ['CDI']
621b885c6919b49c17d4799a ['CDI']
621b885c6919b49c17d4799b []
621b885c6919b49c17d4799c []
621b885c6919b49c17d4799d []
621b885c6919b49c17d4799e ['CDI']
621b885c6919b49c17d4799f ['CDI']
621b885c6919b49c17d479a0 ['CDI', 'CDI']
621b885c6919b49c17d479a1 []
621b885c6919b49c17d479a2 []
621b885c6919b49c17d479a3 []
621b885c6919b49c17d479a4 []
621b885c6919b49c17d479a5 ['CDI']
621b885c6919b49c17d479a6 ['CDI']
621b885c6919b49c17d479a7 ['CDI']
621b885c6919b49c17d479a8 []
621b885c6919b49c17d479a9 []
621b885c6919b49c17d479aa ['CDI', 'CDI']
621b885c6919b49c17d479ab []
621b885c6919b49c17d479ac ['CDI']
621b885c6919b49c17d479ad ['CDI']

621b885c6919b49c17d479ae []
621b885c6919b49c17d479af []
621b885c6919b49c17d479b0 []
621b885c6919b49c17d479b1 ['CDI']
621b885c6919b49c17d479b2 ['CDI']
621b885c6919b49c17d479b3 ['CDI']
621b885c6919b49c17d479b4 ['CDI']
621b885c6919b49c17d479b5 []
621b885c6919b49c17d479b6 []
621b885c6919b49c17d479b7 []
621b885c6919b49c17d479b8 []
621b885c6919b49c17d479b9 []
621b885c6919b49c17d479ba ['CDI', 'CDI']
621b885c6919b49c17d479bb ['CDI']
621b885c6919b49c17d479bc []
621b885c6919b49c17d479bd []
621b885c6919b49c17d479be []
621b885c6919b49c17d479bf []
621b885c6919b49c17d479c0 []
621b885c6919b49c17d479c1 []
621b885c6919b49c17d479c2 []
621b885c6919b49c17d479c3 ['CDI']
621b885c6919b49c17d479c4 []
621b885c6919b49c17d479c5 []
621b885c6919b49c17d479c6 []
621b885c6919b49c17d479c7 []
621b885c6919b49c17d479c8 []
621b885c6919b49c17d479c9 []
621b885c6919b49c17d479ca []
621b885c6919b49c17d479cb []
621b885c6919b49c17d479cc []
621b885c6919b49c17d479cd []
621b885c6919b49c17d479ce []
621b885c6919b49c17d479cf ['CDI']
621b885c6919b49c17d479d0 []
621b885c6919b49c17d479d1 []
621b885c6919b49c17d479d2 ['CDI']
621b885c6919b49c17d479d3 []
621b885c6919b49c17d479d4 []
621b885c6919b49c17d479d5 ['CDI']
621b885c6919b49c17d479d6 ['CDI']
621b885c6919b49c17d479d7 ['CDI', 'CDI']
621b885c6919b49c17d479d8 ['CDI']
621b885c6919b49c17d479d9 []
621b885c6919b49c17d479da ['CDI']
621b885c6919b49c17d479db ['CDI']
621b885c6919b49c17d479dc []
621b885c6919b49c17d479dd []
621b885c6919b49c17d479de []
621b885c6919b49c17d479df []
621b885c6919b49c17d479e0 []
621b885c6919b49c17d479e1 ['CDI', 'CDI']
621b885c6919b49c17d479e2 ['CDI', 'CDI']
621b885c6919b49c17d479e3 ['CDI']
621b885c6919b49c17d479e4 ['CDI']
621b885c6919b49c17d479e5 ['CDI', 'CDI']
621b885c6919b49c17d479e6 ['CDI']
621b885c6919b49c17d479e7 ['CDI']
621b885c6919b49c17d479e8 ['CDI']
621b885c6919b49c17d479e9 ['CDI']
621b885c6919b49c17d479ea ['CDI', 'CDI']
621b885c6919b49c17d479eb ['CDI', 'CDI']
621b885c6919b49c17d479ec []
621b885c6919b49c17d479ed []
621b885c6919b49c17d479ee []
621b885c6919b49c17d479ef []
621b885c6919b49c17d479f0 ['CDI']
621b885c6919b49c17d479f1 ['CDI']
621b885c6919b49c17d479f2 ['CDI']
621b885c6919b49c17d479f3 ['CDI']
621b885c6919b49c17d479f4 ['CDI']
621b885c6919b49c17d479f5 []
621b885c6919b49c17d479f6 ['CDI']
621b885c6919b49c17d479f7 ['CDI']
621b885c6919b49c17d479f8 ['CDI']
621b885c6919b49c17d479f9 ['CDI']
621b885c6919b49c17d479fa []
621b885c6919b49c17d479fb []
621b885c6919b49c17d479fc ['CDI']
621b885c6919b49c17d479fd ['CDI']
621b885c6919b49c17d479fe ['CDI']
621b885c6919b49c17d479ff ['CDI']
621b885c6919b49c17d47a00 []
621b885c6919b49c17d47a01 []
621b885c6919b49c17d47a02 []
621b885c6919b49c17d47a03 ['CDI', 'CDI']
621b885c6919b49c17d47a04 ['CDI']
621b885c6919b49c17d47a05 ['CDI']
621b885c6919b49c17d47a06 ['CDI', 'CDI']
621b885c6919b49c17d47a07 ['CDI', 'CDI']
621b885c6919b49c17d47a08 ['CDI', 'CDI']
621b885c6919b49c17d47a09 ['CDI', 'CDI']
621b885c6919b49c17d47a0a ['CDI', 'CDI']
621b885c6919b49c17d47a0b ['CDI']
621b885c6919b49c17d47a0c ['CDI', 'CDI']
621b885c6919b49c17d47a0d ['CDI', 'CDI']
621b885c6919b49c17d47a0e ['CDI', 'CDI']
621b885c6919b49c17d47a0f ['CDI', 'CDI']
621b885c6919b49c17d47a10 ['CDI', 'CDI']
621b885c6919b49c17d47a11 ['CDI', 'CDI']
621b885c6919b49c17d47a12 ['CDI', 'CDI']
621b885c6919b49c17d47a13 ['CDI', 'CDI']
621b885c6919b49c17d47a14 ['CDI']
621b885c6919b49c17d47a15 ['CDI']
621b885c6919b49c17d47a16 ['CDI']
621b885c6919b49c17d47a17 []
621b885c6919b49c17d47a18 []
621b885c6919b49c17d47a19 ['CDI']
621b885c6919b49c17d47a1a []
621b885c6919b49c17d47a1b ['CDI']
621b885c6919b49c17d47a1c []
621b885c6919b49c17d47a1d ['CDI', 'CDI']
621b885c6919b49c17d47a1e ['CDI', 'CDI']
621b885c6919b49c17d47a1f []
621b885c6919b49c17d47a20 []
621b885c6919b49c17d47a21 []
621b885c6919b49c17d47a22 ['CDI', 'CDI']
621b885c6919b49c17d47a23 ['CDI', 'CDI']
621b885c6919b49c17d47a24 ['CDI', 'CDI']
621b885c6919b49c17d47a25 ['CDI', 'CDI']
621b885c6919b49c17d47a26 ['CDI', 'CDI']
621b885c6919b49c17d47a27 []
621b885c6919b49c17d47a28 ['CDI', 'CDI']
621b885c6919b49c17d47a29 ['CDI', 'CDI']
621b885c6919b49c17d47a2a ['CDI']
621b885c6919b49c17d47a2b ['CDI']
621b885c6919b49c17d47a2c []
621b885c6919b49c17d47a2d ['CDI']
621b885c6919b49c17d47a2e []
621b885c6919b49c17d47a2f []
621b885c6919b49c17d47a30 []
621b885c6919b49c17d47a31 []
621b885c6919b49c17d47a32 []
621b885c6919b49c17d47a33 []
621b885c6919b49c17d47a34 []
621b885c6919b49c17d47a35 []
621b885c6919b49c17d47a36 ['CDI']
621b885c6919b49c17d47a37 []
621b885c6919b49c17d47a38 []
621b885c6919b49c17d47a39 []
621b885c6919b49c17d47a3a []
621b885c6919b49c17d47a3b ['CDI', 'CDI']
621b885c6919b49c17d47a3c []
621b885c6919b49c17d47a3d []
621b885c6919b49c17d47a3e []
621b885c6919b49c17d47a3f ['CDI']
621b885c6919b49c17d47a40 ['CDI']
621b885c6919b49c17d47a41 ['CDI']
621b885c6919b49c17d47a42 []
621b885c6919b49c17d47a43 ['CDI']
621b885c6919b49c17d47a44 []
621b885c6919b49c17d47a45 ['CDI']
621b885c6919b49c17d47a46 ['CDI']
621b885c6919b49c17d47a47 []
621b885c6919b49c17d47a48 ['CDI']
621b885c6919b49c17d47a49 []
621b885c6919b49c17d47a4a []
621b885c6919b49c17d47a4b []
621b885c6919b49c17d47a4c []
621b885c6919b49c17d47a4d ['CDI']
621b885c6919b49c17d47a4e []
621b885c6919b49c17d47a4f []
621b885c6919b49c17d47a50 ['CDI']
621b885c6919b49c17d47a51 ['CDI']
621b885c6919b49c17d47a52 ['CDI']
621b885c6919b49c17d47a53 ['CDI']
621b885c6919b49c17d47a54 ['CDI']
621b885c6919b49c17d47a55 ['CDI']
621b885c6919b49c17d47a56 ['CDI']
621b885c6919b49c17d47a57 ['CDI']
621b885c6919b49c17d47a58 []
621b885c6919b49c17d47a59 []
621b885c6919b49c17d47a5a ['CDI']
621b885c6919b49c17d47a5b ['CDI']
621b885c6919b49c17d47a5c ['CDI']
621b885c6919b49c17d47a5d []
621b885c6919b49c17d47a5e []
621b885c6919b49c17d47a5f ['CDI']
621b885c6919b49c17d47a60 ['CDI']
621b885c6919b49c17d47a61 ['CDI']
621b885c6919b49c17d47a62 ['CDI', 'CDI']
621b885c6919b49c17d47a63 ['CDI', 'CDI']
621b885c6919b49c17d47a64 ['CDI', 'CDI']
621b885c6919b49c17d47a65 []
621b885c6919b49c17d47a66 ['CDI']
621b885c6919b49c17d47a67 ['CDI']
621b885c6919b49c17d47a68 ['CDI']
621b885c6919b49c17d47a69 []
621b885c6919b49c17d47a6a []
621b885c6919b49c17d47a6b ['CDI']
621b885c6919b49c17d47a6c []
621b885c6919b49c17d47a6d ['CDI']
621b885c6919b49c17d47a6e ['CDI']
621b885c6919b49c17d47a6f ['CDI', 'CDI']
621b885c6919b49c17d47a70 ['CDI']
621b885c6919b49c17d47a71 ['CDI']
621b885c6919b49c17d47a72 ['CDI']
621b885c6919b49c17d47a73 ['CDI', 'CDI']
621b885c6919b49c17d47a74 ['CDI']
621b885c6919b49c17d47a75 ['CDI']
621b885c6919b49c17d47a76 []
621b885c6919b49c17d47a77 ['CDI']
621b885c6919b49c17d47a78 ['CDI']
621b885c6919b49c17d47a79 ['CDI', 'CDI']
621b885c6919b49c17d47a7a []
621b885c6919b49c17d47a7b ['CDI']
621b885c6919b49c17d47a7c ['CDI', 'CDI']
621b885c6919b49c17d47a7d ['CDI']
621b885c6919b49c17d47a7e ['CDI']
621b885c6919b49c17d47a7f []
621b885c6919b49c17d47a80 []
621b885c6919b49c17d47a81 []
621b885c6919b49c17d47a82 ['CDI', 'CDI']
621b885c6919b49c17d47a83 []
621b885c6919b49c17d47a84 ['CDI', 'CDI']
621b885c6919b49c17d47a85 []
621b885c6919b49c17d47a86 []
621b885c6919b49c17d47a87 ['CDI']
621b885c6919b49c17d47a88 ['CDI']
621b885c6919b49c17d47a89 ['CDI']
621b885c6919b49c17d47a8a []
621b885c6919b49c17d47a8b []
621b885c6919b49c17d47a8c ['CDI']
621b885c6919b49c17d47a8d ['CDI']
621b885c6919b49c17d47a8e ['CDI']
621b885c6919b49c17d47a8f []
621b885c6919b49c17d47a90 ['CDI', 'CDI']
621b885c6919b49c17d47a91 ['CDI', 'CDI']
621b885c6919b49c17d47a92 ['CDI']
621b885c6919b49c17d47a93 ['CDI']
621b885c6919b49c17d47a94 []
621b885c6919b49c17d47a95 []
621b885c6919b49c17d47a96 ['CDI']
621b885c6919b49c17d47a97 ['CDI', 'CDI']
621b885c6919b49c17d47a98 ['CDI']
621b885c6919b49c17d47a99 []
621b885c6919b49c17d47a9a []
621b885c6919b49c17d47a9b ['CDI']
621b885c6919b49c17d47a9c []
621b885c6919b49c17d47a9d ['CDI']
621b885c6919b49c17d47a9e []
621b885c6919b49c17d47a9f []
621b885c6919b49c17d47aa0 ['CDI', 'CDI']
621b885c6919b49c17d47aa1 []
621b885c6919b49c17d47aa2 ['CDI']
621b885c6919b49c17d47aa3 ['CDI']
621b885c6919b49c17d47aa4 ['CDI']
621b885c6919b49c17d47aa5 []
621b885c6919b49c17d47aa6 ['CDI']
621b885c6919b49c17d47aa7 ['CDI']
621b885c6919b49c17d47aa8 []
621b885c6919b49c17d47aa9 []
621b885c6919b49c17d47aaa []
621b885c6919b49c17d47aab []
621b885c6919b49c17d47aac ['CDI']
621b885c6919b49c17d47aad []

621b885c6919b49c17d47aae []
621b885c6919b49c17d47aaf []
621b885c6919b49c17d47ab0 []
621b885c6919b49c17d47ab1 []
621b885c6919b49c17d47ab2 []
621b885c6919b49c17d47ab3 ['CDI']
621b885c6919b49c17d47ab4 []
621b885c6919b49c17d47ab5 ['CDI', 'CDI']
621b885c6919b49c17d47ab6 ['CDI']
621b885c6919b49c17d47ab7 ['CDI']
621b885c6919b49c17d47ab8 ['CDI']
621b885c6919b49c17d47ab9 ['CDI']
621b885c6919b49c17d47aba ['CDI', 'CDI']
621b885c6919b49c17d47abb []
621b885c6919b49c17d47abc ['CDI', 'CDI']
621b885c6919b49c17d47abd []
621b885c6919b49c17d47abe ['CDI', 'CDI']
621b885c6919b49c17d47abf ['CDI', 'CDI']
621b885c6919b49c17d47ac0 ['CDI', 'CDI']
621b885c6919b49c17d47ac1 ['CDI']
621b885c6919b49c17d47ac2 ['CDI']
621b885c6919b49c17d47ac3 ['CDI', 'CDI']
621b885c6919b49c17d47ac4 ['CDI']
621b885c6919b49c17d47ac5 []
621b885c6919b49c17d47ac6 ['CDI', 'CDI']
621b885c6919b49c17d47ac7 ['CDI']
621b885c6919b49c17d47ac8 ['CDI']
621b885c6919b49c17d47ac9 ['CDI']
621b885c6919b49c17d47aca ['CDI', 'CDI']
621b885c6919b49c17d47acb ['CDI']
621b885c6919b49c17d47acc []
621b885c6919b49c17d47acd ['CDI']
621b885c6919b49c17d47ace ['CDI']
621b885c6919b49c17d47acf ['CDI']
621b885c6919b49c17d47ad0 ['CDI']
621b885c6919b49c17d47ad1 ['CDI', 'CDI']
621b885c6919b49c17d47ad2 ['CDI']
621b885c6919b49c17d47ad3 ['CDI']
621b885c6919b49c17d47ad4 ['CDI']
621b885c6919b49c17d47ad5 []
621b885c6919b49c17d47ad6 ['CDI', 'CDI', 'CDI']
621b885c6919b49c17d47ad7 []
621b885c6919b49c17d47ad8 ['CDI']
621b885c6919b49c17d47ad9 ['CDI']
621b885c6919b49c17d47ada []
621b885c6919b49c17d47adb []
621b885c6919b49c17d47adc []
621b885c6919b49c17d47add []
621b885c6919b49c17d47ade ['CDI']
621b885c6919b49c17d47adf []
621b885c6919b49c17d47ae0 ['CDI']
621b885c6919b49c17d47ae1 ['CDI']
621b885c6919b49c17d47ae2 []
621b885c6919b49c17d47ae3 []
621b885c6919b49c17d47ae4 []
621b885c6919b49c17d47ae5 []
621b885c6919b49c17d47ae6 []
621b885c6919b49c17d47ae7 ['CDI', 'CDI', 'CDI']
621b885c6919b49c17d47ae8 []

In [195]:
# Récuperation dans un dataframe pandas
df = pd.DataFrame(list(collec.find()))

In [196]:
df.shape

(822, 49)

In [197]:
df = df.drop(columns=['_id', 'Synopsis'])
df.head()

,Title,Company,Salaire_annuel_moyen,Département,Titre/Data,Titre/Data Analyst,Titre/Data Scientist,Titre/Developpeur,Titre/Business Intelligence,Titre/Consultant,...,C++,SQL,NoSQL,AWS,Azure,Kafka,SQL Server,Machine_learning,deep_learning,English
0,Data Analyst H/F,ACII,40000.0,37,1,1,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
1,Développeur Java & PHP - Full stack - H/F,Golden Bees,34000.0,75,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
2,Développeur COBOL - RDZ (H/F) / Freelance,HR-TEAM,410.0,75,0,0,0,1,0,0,...,0,1,0,1,0,0,0,0,0,0
3,Développeur Python/ Django (H/F) / Freelance,HR-TEAM,475.0,75,0,0,0,1,0,0,...,0,0,0,0,4,0,0,0,0,0
4,Devops Engineer (H/F) / Freelance,HR-TEAM,575.0,75,0,0,0,0,0,0,...,0,0,0,0,4,0,0,0,0,0

In [198]:
df.shape

(822, 47)

In [199]:
#df.to_csv('20220227_Indeed_Project_7_to_machine_learning.csv', encoding='utf-8')

In [ ]:
df = df_more

In [ ]:
class Preprocess():
    def __init__(self,df):
        
        self.df_ = df   
        
        def isFreelance(txt):
            if bool(re.search("freelance", txt)):
                return 1
            else:
                return 0

        def isDataAnalyst(txt):
            if bool(re.search("(?=.*scientist)(?=.*data)", txt)):
                return 1
            else:
                return 0

        def isDataScintist(txt):
            if bool(re.search("(?=.*analyst)(?=.*donné)", txt))|bool(re.search("(?=.*analyst)(?=.*data)", txt)):
                return 1
            else:
                return 0

        def isConfirm(txt):
            if bool(re.search("(?=.*confirm)", txt))|bool(re.search("(?=.*senior)", txt)):
                return 1
            else:
                return 0
        
        self.df_['LocNum'] = df['Location'].str.extract(r'(\d{2})', expand=False)
        # lb_encod = OrdinalEncoder()
        # self.df_['LocNum'] = lb_encod.fit_transform(self.df_['LocNum'])
        
        self.df_['freelance'] = self.df_['Title'].map(isFreelance)
        self.df_['DataScientist'] = self.df_['Title'].map(isDataAnalyst)
        self.df_['DataAnalyste'] = self.df_['Title'].map(isDataScintist)
        self.df_['senior'] = self.df_['Title'].map(isConfirm)
        self.df_.drop(self.df_[self.df_.Average<20000].index, inplace=True)
        
        self.X = self.df_.drop(columns=['Average','Title','Location','Synopsis','Company','Rating','Low','High'])
        self.y = self.df_['Average']
    
    
    def getDf(self):
        return self.df_
        
    def getFeatures(self):
        return self.X
    
    def getTarget(self):
        return self.y

In [ ]:
preproc = Preprocess(df)
df = preproc.getDf()
X = preproc.getFeatures()
y = preproc.getTarget()

In [ ]:
X

In [ ]:
y